/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetTimetableGroupsGetForCohortByCohortId200ResponseInner
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostTimetableGroupsSelect200Response
import hu.petrik.filcapp.api.model.PostTimetableGroupsSelectRequest

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class GroupApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Get the groups of a cohort, marking the current user selection.
     * @param cohortId 
     * @return kotlin.collections.List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableGroupsGetForCohortByCohortId(cohortId: kotlin.String): HttpResponse<kotlin.collections.List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner>> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/groups/getForCohort/{cohortId}".replace("{" + "cohortId" + "}", "$cohortId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableGroupsGetForCohortByCohortIdResponse>().map { value }
    }

    @Serializable(GetTimetableGroupsGetForCohortByCohortIdResponse.Companion::class)
    private class GetTimetableGroupsGetForCohortByCohortIdResponse(val value: List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner>) {
        companion object : KSerializer<GetTimetableGroupsGetForCohortByCohortIdResponse> {
            private val serializer: KSerializer<List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner>> = serializer<List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableGroupsGetForCohortByCohortIdResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableGroupsGetForCohortByCohortIdResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Select the group the current user belongs to for a division. Replaces any previous membership in that division.
     * @param postTimetableGroupsSelectRequest 
     * @return PostTimetableGroupsSelect200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postTimetableGroupsSelect(postTimetableGroupsSelectRequest: PostTimetableGroupsSelectRequest): HttpResponse<PostTimetableGroupsSelect200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postTimetableGroupsSelectRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/timetable/groups/select",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
