/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetKiosk200Response
import hu.petrik.filcapp.api.model.GetKioskNews200Response
import hu.petrik.filcapp.api.model.GetKioskPetrikNews200Response
import hu.petrik.filcapp.api.model.GetKioskWeather200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostKiosk201Response
import hu.petrik.filcapp.api.model.PostKioskDepartures200Response
import hu.petrik.filcapp.api.model.PostKioskDeparturesRequest
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200Response
import hu.petrik.filcapp.api.model.PostKioskHeartbeatRequest
import hu.petrik.filcapp.api.model.PostKioskRequest
import hu.petrik.filcapp.api.model.PutKioskByIdRequest

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class KioskApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Delete a kiosk
     * @param id 
     * @return PostKiosk201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteKioskById(id: kotlin.String): HttpResponse<PostKiosk201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/kiosk/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List all kiosks
     * @return GetKiosk200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getKiosk(): HttpResponse<GetKiosk200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/kiosk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Active, titled, non-cohort-scoped announcements for the TV kiosk marquee
     * @return GetKioskNews200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getKioskNews(): HttpResponse<GetKioskNews200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/kiosk/news",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * The image an announcement shows on the kiosk, as stored
     * @param id 
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getKioskNewsByIdImage(id: kotlin.String): HttpResponse<kotlin.String> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/kiosk/news/{id}/image".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * petrik.hu news for the navigator kiosk, cached for ten minutes
     * @param machine  (optional)
     * @return GetKioskPetrikNews200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getKioskPetrikNews(machine: kotlin.String? = null): HttpResponse<GetKioskPetrikNews200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        machine?.apply { localVariableQuery["machine"] = listOf("$machine") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/kiosk/petrik-news",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Current weather for the TV kiosk, cached for ten minutes
     * @return GetKioskWeather200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getKioskWeather(): HttpResponse<GetKioskWeather200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/kiosk/weather",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Register a kiosk
     * @param postKioskRequest 
     * @return PostKiosk201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postKiosk(postKioskRequest: PostKioskRequest): HttpResponse<PostKiosk201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postKioskRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/kiosk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Next departure per configured group, trying each stop in order
     * @param postKioskDeparturesRequest 
     * @return PostKioskDepartures200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postKioskDepartures(postKioskDeparturesRequest: PostKioskDeparturesRequest): HttpResponse<PostKioskDepartures200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = postKioskDeparturesRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/kiosk/departures",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Record a kiosk heartbeat and report whether the box is registered and enabled
     * @param postKioskHeartbeatRequest 
     * @return PostKioskHeartbeat200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postKioskHeartbeat(postKioskHeartbeatRequest: PostKioskHeartbeatRequest): HttpResponse<PostKioskHeartbeat200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = postKioskHeartbeatRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/kiosk/heartbeat",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a kiosk
     * @param id 
     * @param putKioskByIdRequest  (optional)
     * @return PostKiosk201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putKioskById(id: kotlin.String, putKioskByIdRequest: PutKioskByIdRequest? = null): HttpResponse<PostKiosk201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putKioskByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/kiosk/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
