/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForIdByLessonId200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachers200ResponseInner
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachersRequest
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetSubstitutionCandidates200Response
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetSubstitutionCandidatesRequest

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class LessonApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Get lessons for a given cohort from the database.
     * @param cohortId 
     * @param timetableId  (optional)
     * @return kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableLessonsGetForCohortByCohortId(cohortId: kotlin.String, timetableId: kotlin.String? = null): HttpResponse<kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        timetableId?.apply { localVariableQuery["timetableId"] = listOf("$timetableId") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/lessons/getForCohort/{cohortId}".replace("{" + "cohortId" + "}", "$cohortId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableLessonsGetForCohortByCohortIdResponse>().map { value }
    }

    @Serializable(GetTimetableLessonsGetForCohortByCohortIdResponse.Companion::class)
    private class GetTimetableLessonsGetForCohortByCohortIdResponse(val value: List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>) {
        companion object : KSerializer<GetTimetableLessonsGetForCohortByCohortIdResponse> {
            private val serializer: KSerializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> = serializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableLessonsGetForCohortByCohortIdResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableLessonsGetForCohortByCohortIdResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get a lesson by its ID from the database.
     * @param lessonId 
     * @return GetTimetableLessonsGetForIdByLessonId200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableLessonsGetForIdByLessonId(lessonId: kotlin.String): HttpResponse<GetTimetableLessonsGetForIdByLessonId200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/lessons/getForId/{lessonId}".replace("{" + "lessonId" + "}", "$lessonId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Get lessons for a given classroom from the database.
     * @param classroomId 
     * @param timetableId  (optional)
     * @return kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableLessonsGetForRoomByClassroomId(classroomId: kotlin.String, timetableId: kotlin.String? = null): HttpResponse<kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        timetableId?.apply { localVariableQuery["timetableId"] = listOf("$timetableId") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/lessons/getForRoom/{classroomId}".replace("{" + "classroomId" + "}", "$classroomId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableLessonsGetForRoomByClassroomIdResponse>().map { value }
    }

    @Serializable(GetTimetableLessonsGetForRoomByClassroomIdResponse.Companion::class)
    private class GetTimetableLessonsGetForRoomByClassroomIdResponse(val value: List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>) {
        companion object : KSerializer<GetTimetableLessonsGetForRoomByClassroomIdResponse> {
            private val serializer: KSerializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> = serializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableLessonsGetForRoomByClassroomIdResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableLessonsGetForRoomByClassroomIdResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get lessons for a given teacher from the database.
     * @param teacherId 
     * @param timetableId  (optional)
     * @return kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableLessonsGetForTeacherByTeacherId(teacherId: kotlin.String, timetableId: kotlin.String? = null): HttpResponse<kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        timetableId?.apply { localVariableQuery["timetableId"] = listOf("$timetableId") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/lessons/getForTeacher/{teacherId}".replace("{" + "teacherId" + "}", "$teacherId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableLessonsGetForTeacherByTeacherIdResponse>().map { value }
    }

    @Serializable(GetTimetableLessonsGetForTeacherByTeacherIdResponse.Companion::class)
    private class GetTimetableLessonsGetForTeacherByTeacherIdResponse(val value: List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>) {
        companion object : KSerializer<GetTimetableLessonsGetForTeacherByTeacherIdResponse> {
            private val serializer: KSerializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>> = serializer<List<GetTimetableLessonsGetForCohortByCohortId200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableLessonsGetForTeacherByTeacherIdResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableLessonsGetForTeacherByTeacherIdResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get lessons for multiple teachers in a single request.
     * @param postTimetableLessonsGetForTeachersRequest 
     * @return kotlin.collections.List<PostTimetableLessonsGetForTeachers200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postTimetableLessonsGetForTeachers(postTimetableLessonsGetForTeachersRequest: PostTimetableLessonsGetForTeachersRequest): HttpResponse<kotlin.collections.List<PostTimetableLessonsGetForTeachers200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = postTimetableLessonsGetForTeachersRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/timetable/lessons/getForTeachers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<PostTimetableLessonsGetForTeachersResponse>().map { value }
    }


    @Serializable(PostTimetableLessonsGetForTeachersResponse.Companion::class)
    private class PostTimetableLessonsGetForTeachersResponse(val value: List<PostTimetableLessonsGetForTeachers200ResponseInner>) {
        companion object : KSerializer<PostTimetableLessonsGetForTeachersResponse> {
            private val serializer: KSerializer<List<PostTimetableLessonsGetForTeachers200ResponseInner>> = serializer<List<PostTimetableLessonsGetForTeachers200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: PostTimetableLessonsGetForTeachersResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = PostTimetableLessonsGetForTeachersResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get available lessons and substitute teacher candidates for substitution editing in one request.
     * @param postTimetableLessonsGetSubstitutionCandidatesRequest 
     * @return PostTimetableLessonsGetSubstitutionCandidates200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postTimetableLessonsGetSubstitutionCandidates(postTimetableLessonsGetSubstitutionCandidatesRequest: PostTimetableLessonsGetSubstitutionCandidatesRequest): HttpResponse<PostTimetableLessonsGetSubstitutionCandidates200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = postTimetableLessonsGetSubstitutionCandidatesRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/timetable/lessons/getSubstitutionCandidates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
