/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetNavigatorBuildings200Response
import hu.petrik.filcapp.api.model.GetNavigatorClassroomTypes200Response
import hu.petrik.filcapp.api.model.GetNavigatorClassrooms200Response
import hu.petrik.filcapp.api.model.GetNavigatorCorridors200Response
import hu.petrik.filcapp.api.model.GetNavigatorGraph200Response
import hu.petrik.filcapp.api.model.GetNavigatorLifts200Response
import hu.petrik.filcapp.api.model.GetNavigatorStairs200Response
import hu.petrik.filcapp.api.model.GetNavigatorTranslations200Response
import hu.petrik.filcapp.api.model.GetNavigatorTranslationsAvailable200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostNavigatorBuildings201Response
import hu.petrik.filcapp.api.model.PostNavigatorBuildingsRequest
import hu.petrik.filcapp.api.model.PostNavigatorClassroomTypes201Response
import hu.petrik.filcapp.api.model.PostNavigatorClassroomTypesRequest
import hu.petrik.filcapp.api.model.PostNavigatorClassrooms201Response
import hu.petrik.filcapp.api.model.PostNavigatorClassroomsRequest
import hu.petrik.filcapp.api.model.PostNavigatorCorridors201Response
import hu.petrik.filcapp.api.model.PostNavigatorCorridorsRequest
import hu.petrik.filcapp.api.model.PostNavigatorImport200Response
import hu.petrik.filcapp.api.model.PostNavigatorImportRequest
import hu.petrik.filcapp.api.model.PostNavigatorLifts201Response
import hu.petrik.filcapp.api.model.PostNavigatorLiftsRequest
import hu.petrik.filcapp.api.model.PostNavigatorStairs201Response
import hu.petrik.filcapp.api.model.PostNavigatorStairsRequest
import hu.petrik.filcapp.api.model.PostNavigatorTranslations201Response
import hu.petrik.filcapp.api.model.PostNavigatorTranslationsRequest
import hu.petrik.filcapp.api.model.PutNavigatorBuildingsByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorClassroomTypesByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorClassroomsById200Response
import hu.petrik.filcapp.api.model.PutNavigatorClassroomsByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorCorridorsByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorLiftsByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorStairsByIdRequest
import hu.petrik.filcapp.api.model.PutNavigatorTranslationsByLangByKey200Response
import hu.petrik.filcapp.api.model.PutNavigatorTranslationsByLangByKeyRequest

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class NavigatorApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Delete a campus building; its corridors, lifts and stairs cascade with it, but rooms still assigned to it refuse the delete
     * @param id 
     * @return PostNavigatorBuildings201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorBuildingsById(id: kotlin.String): HttpResponse<PostNavigatorBuildings201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/buildings/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete a classroom type; types still assigned to a classroom are refused
     * @param id 
     * @return PostNavigatorClassroomTypes201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorClassroomTypesById(id: kotlin.String): HttpResponse<PostNavigatorClassroomTypes201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/classroom-types/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete a classroom; rooms the timetable still uses are refused
     * @param id 
     * @return PutNavigatorClassroomsById200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorClassroomsById(id: kotlin.String): HttpResponse<PutNavigatorClassroomsById200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/classrooms/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete a corridor
     * @param id 
     * @return PostNavigatorCorridors201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorCorridorsById(id: kotlin.String): HttpResponse<PostNavigatorCorridors201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/corridors/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete a lift
     * @param id 
     * @return PostNavigatorLifts201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorLiftsById(id: kotlin.String): HttpResponse<PostNavigatorLifts201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/lifts/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete a staircase
     * @param id 
     * @return PostNavigatorStairs201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorStairsById(id: kotlin.String): HttpResponse<PostNavigatorStairs201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/stairs/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Delete one codename in one language
     * @param lang 
     * @param key 
     * @return PutNavigatorTranslationsByLangByKey200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun deleteNavigatorTranslationsByLangByKey(lang: kotlin.String, key: kotlin.String): HttpResponse<PutNavigatorTranslationsByLangByKey200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/navigator/translations/{lang}/{key}".replace("{" + "lang" + "}", "$lang").replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the campus buildings
     * @return GetNavigatorBuildings200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorBuildings(): HttpResponse<GetNavigatorBuildings200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/buildings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the classroom types
     * @return GetNavigatorClassroomTypes200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorClassroomTypes(): HttpResponse<GetNavigatorClassroomTypes200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/classroom-types",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the classrooms, including the ones the campus has not placed yet
     * @return GetNavigatorClassrooms200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorClassrooms(): HttpResponse<GetNavigatorClassrooms200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/classrooms",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the corridors
     * @return GetNavigatorCorridors200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorCorridors(): HttpResponse<GetNavigatorCorridors200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/corridors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Export every navigator row (buildings, classroom types, classrooms, corridors, lifts, stairs and translations) as a versioned JSON payload.
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorExport(): HttpResponse<kotlin.String> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/export",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * The whole campus graph in the upstream wire format, without a session. Only rows the campus has placed on the map appear.
     * @return GetNavigatorGraph200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorGraph(): HttpResponse<GetNavigatorGraph200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/graph",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the lifts
     * @return GetNavigatorLifts200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorLifts(): HttpResponse<GetNavigatorLifts200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/lifts",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the staircases
     * @return GetNavigatorStairs200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorStairs(): HttpResponse<GetNavigatorStairs200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/stairs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List every translation row
     * @return GetNavigatorTranslations200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorTranslations(): HttpResponse<GetNavigatorTranslations200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/translations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * List the languages the campus translations exist in
     * @return GetNavigatorTranslationsAvailable200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorTranslationsAvailable(): HttpResponse<GetNavigatorTranslationsAvailable200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/translations/available",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * One language as a flat &#x60;text_key -&gt; text&#x60; bundle, without a session
     * @param lang 
     * @return kotlin.collections.Map<kotlin.String, kotlin.String>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getNavigatorTranslationsLang(lang: kotlin.String): HttpResponse<kotlin.collections.Map<kotlin.String, kotlin.String>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        lang?.apply { localVariableQuery["lang"] = listOf("$lang") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/navigator/translations/lang",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetNavigatorTranslationsLangResponse>().map { value }
    }

    @Serializable(GetNavigatorTranslationsLangResponse.Companion::class)
    private class GetNavigatorTranslationsLangResponse(val value: Map<kotlin.String, kotlin.String>) {
        companion object : KSerializer<GetNavigatorTranslationsLangResponse> {
            private val serializer: KSerializer<Map<kotlin.String, kotlin.String>> = serializer<Map<String, kotlin.String>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetNavigatorTranslationsLangResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetNavigatorTranslationsLangResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Create a campus building
     * @param postNavigatorBuildingsRequest 
     * @return PostNavigatorBuildings201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorBuildings(postNavigatorBuildingsRequest: PostNavigatorBuildingsRequest): HttpResponse<PostNavigatorBuildings201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorBuildingsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/buildings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create a classroom type
     * @param postNavigatorClassroomTypesRequest 
     * @return PostNavigatorClassroomTypes201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorClassroomTypes(postNavigatorClassroomTypesRequest: PostNavigatorClassroomTypesRequest): HttpResponse<PostNavigatorClassroomTypes201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorClassroomTypesRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/classroom-types",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create a classroom
     * @param postNavigatorClassroomsRequest 
     * @return PostNavigatorClassrooms201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorClassrooms(postNavigatorClassroomsRequest: PostNavigatorClassroomsRequest): HttpResponse<PostNavigatorClassrooms201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorClassroomsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/classrooms",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create a corridor
     * @param postNavigatorCorridorsRequest 
     * @return PostNavigatorCorridors201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorCorridors(postNavigatorCorridorsRequest: PostNavigatorCorridorsRequest): HttpResponse<PostNavigatorCorridors201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorCorridorsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/corridors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Insert or update every collection in a navigator export payload by its key, inside one transaction. Rows absent from the payload are never deleted.
     * @param postNavigatorImportRequest 
     * @return PostNavigatorImport200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorImport(postNavigatorImportRequest: PostNavigatorImportRequest): HttpResponse<PostNavigatorImport200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorImportRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/import",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create a lift
     * @param postNavigatorLiftsRequest 
     * @return PostNavigatorLifts201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorLifts(postNavigatorLiftsRequest: PostNavigatorLiftsRequest): HttpResponse<PostNavigatorLifts201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorLiftsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/lifts",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create a staircase
     * @param postNavigatorStairsRequest 
     * @return PostNavigatorStairs201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorStairs(postNavigatorStairsRequest: PostNavigatorStairsRequest): HttpResponse<PostNavigatorStairs201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorStairsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/stairs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Create or replace one codename across every given language
     * @param postNavigatorTranslationsRequest 
     * @return PostNavigatorTranslations201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun postNavigatorTranslations(postNavigatorTranslationsRequest: PostNavigatorTranslationsRequest): HttpResponse<PostNavigatorTranslations201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = postNavigatorTranslationsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/navigator/translations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a campus building
     * @param id 
     * @param putNavigatorBuildingsByIdRequest  (optional)
     * @return PostNavigatorBuildings201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorBuildingsById(id: kotlin.String, putNavigatorBuildingsByIdRequest: PutNavigatorBuildingsByIdRequest? = null): HttpResponse<PostNavigatorBuildings201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorBuildingsByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/buildings/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a classroom type
     * @param id 
     * @param putNavigatorClassroomTypesByIdRequest  (optional)
     * @return PostNavigatorClassroomTypes201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorClassroomTypesById(id: kotlin.String, putNavigatorClassroomTypesByIdRequest: PutNavigatorClassroomTypesByIdRequest? = null): HttpResponse<PostNavigatorClassroomTypes201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorClassroomTypesByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/classroom-types/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a classroom
     * @param id 
     * @param putNavigatorClassroomsByIdRequest  (optional)
     * @return PutNavigatorClassroomsById200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorClassroomsById(id: kotlin.String, putNavigatorClassroomsByIdRequest: PutNavigatorClassroomsByIdRequest? = null): HttpResponse<PutNavigatorClassroomsById200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorClassroomsByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/classrooms/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a corridor
     * @param id 
     * @param putNavigatorCorridorsByIdRequest  (optional)
     * @return PostNavigatorCorridors201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorCorridorsById(id: kotlin.String, putNavigatorCorridorsByIdRequest: PutNavigatorCorridorsByIdRequest? = null): HttpResponse<PostNavigatorCorridors201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorCorridorsByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/corridors/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a lift
     * @param id 
     * @param putNavigatorLiftsByIdRequest  (optional)
     * @return PostNavigatorLifts201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorLiftsById(id: kotlin.String, putNavigatorLiftsByIdRequest: PutNavigatorLiftsByIdRequest? = null): HttpResponse<PostNavigatorLifts201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorLiftsByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/lifts/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Update a staircase
     * @param id 
     * @param putNavigatorStairsByIdRequest  (optional)
     * @return PostNavigatorStairs201Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorStairsById(id: kotlin.String, putNavigatorStairsByIdRequest: PutNavigatorStairsByIdRequest? = null): HttpResponse<PostNavigatorStairs201Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorStairsByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/stairs/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * Write the text of one codename in one language
     * @param lang 
     * @param key 
     * @param putNavigatorTranslationsByLangByKeyRequest 
     * @return PutNavigatorTranslationsByLangByKey200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun putNavigatorTranslationsByLangByKey(lang: kotlin.String, key: kotlin.String, putNavigatorTranslationsByLangByKeyRequest: PutNavigatorTranslationsByLangByKeyRequest): HttpResponse<PutNavigatorTranslationsByLangByKey200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = putNavigatorTranslationsByLangByKeyRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/navigator/translations/{lang}/{key}".replace("{" + "lang" + "}", "$lang").replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
