/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetTimetablePeriodsGetAll200ResponseInner
import hu.petrik.filcapp.api.model.PostBugReport400Response

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class PeriodApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Get all period definitions used in a given timetable, sorted by period number.
     * @param timetableId  (optional)
     * @return kotlin.collections.List<GetTimetablePeriodsGetAll200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetablePeriodsGetAll(timetableId: kotlin.String? = null): HttpResponse<kotlin.collections.List<GetTimetablePeriodsGetAll200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        timetableId?.apply { localVariableQuery["timetableId"] = listOf("$timetableId") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/periods/getAll",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetablePeriodsGetAllResponse>().map { value }
    }

    @Serializable(GetTimetablePeriodsGetAllResponse.Companion::class)
    private class GetTimetablePeriodsGetAllResponse(val value: List<GetTimetablePeriodsGetAll200ResponseInner>) {
        companion object : KSerializer<GetTimetablePeriodsGetAllResponse> {
            private val serializer: KSerializer<List<GetTimetablePeriodsGetAll200ResponseInner>> = serializer<List<GetTimetablePeriodsGetAll200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetablePeriodsGetAllResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetablePeriodsGetAllResponse(serializer.deserialize(decoder))
        }
    }

}
