/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import hu.petrik.filcapp.api.model.GetTimetableTeachers200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableTeachersGetAll200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableTeachersMe200Response
import hu.petrik.filcapp.api.model.PatchTimetableTeachersById200Response
import hu.petrik.filcapp.api.model.PatchTimetableTeachersByIdRequest
import hu.petrik.filcapp.api.model.PostBugReport400Response

import hu.petrik.filcapp.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class TeacherApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * List all teachers with their email and linked user.
     * @return kotlin.collections.List<GetTimetableTeachers200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableTeachers(): HttpResponse<kotlin.collections.List<GetTimetableTeachers200ResponseInner>> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/teachers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableTeachersResponse>().map { value }
    }

    @Serializable(GetTimetableTeachersResponse.Companion::class)
    private class GetTimetableTeachersResponse(val value: List<GetTimetableTeachers200ResponseInner>) {
        companion object : KSerializer<GetTimetableTeachersResponse> {
            private val serializer: KSerializer<List<GetTimetableTeachers200ResponseInner>> = serializer<List<GetTimetableTeachers200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableTeachersResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableTeachersResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get all teachers from the database.
     * @return kotlin.collections.List<GetTimetableTeachersGetAll200ResponseInner>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableTeachersGetAll(): HttpResponse<kotlin.collections.List<GetTimetableTeachersGetAll200ResponseInner>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/teachers/getAll",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetTimetableTeachersGetAllResponse>().map { value }
    }

    @Serializable(GetTimetableTeachersGetAllResponse.Companion::class)
    private class GetTimetableTeachersGetAllResponse(val value: List<GetTimetableTeachersGetAll200ResponseInner>) {
        companion object : KSerializer<GetTimetableTeachersGetAllResponse> {
            private val serializer: KSerializer<List<GetTimetableTeachersGetAll200ResponseInner>> = serializer<List<GetTimetableTeachersGetAll200ResponseInner>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetTimetableTeachersGetAllResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetTimetableTeachersGetAllResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * 
     * Get the signed-in user&#39;s linked teacher, if any.
     * @return GetTimetableTeachersMe200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getTimetableTeachersMe(): HttpResponse<GetTimetableTeachersMe200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/timetable/teachers/me",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Update a teacher email and/or linked user.
     * @param id 
     * @param patchTimetableTeachersByIdRequest  (optional)
     * @return PatchTimetableTeachersById200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun patchTimetableTeachersById(id: kotlin.String, patchTimetableTeachersByIdRequest: PatchTimetableTeachersByIdRequest? = null): HttpResponse<PatchTimetableTeachersById200Response> {

        val localVariableAuthNames = listOf<String>("sessionAuth")

        val localVariableBody = patchTimetableTeachersByIdRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/timetable/teachers/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
