/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param slug 
 * @param content 
 * @param publishedAt 
 * @param excerpt 
 * @param createdAt 
 * @param updatedAt 
 * @param authorId 
 */
@Serializable

data class Blog (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "content") @Required val content: kotlin.String,

    @SerialName(value = "publishedAt") @Required val publishedAt: kotlin.String?,

    @SerialName(value = "excerpt") val excerpt: kotlin.String? = null,

    @SerialName(value = "createdAt") val createdAt: kotlin.String? = null,

    @SerialName(value = "updatedAt") val updatedAt: kotlin.String? = null,

    @SerialName(value = "authorId") val authorId: kotlin.String? = null

) {


}

