/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetBugReport200ResponseReportsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param reports 
 * @param total 
 */
@Serializable

data class GetBugReport200Response (

    @SerialName(value = "reports") @Required val reports: kotlin.collections.List<GetBugReport200ResponseReportsInner>,

    @SerialName(value = "total") @Required val total: kotlin.Double

) {


}

