/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param message 
 * @param status 
 */
@Serializable

data class GetBugReport400Response (

    @SerialName(value = "code") @Required val code: kotlin.String?,

    @SerialName(value = "message") @Required val message: kotlin.String?,

    @SerialName(value = "status") @Required val status: kotlin.Int

) {


}

