/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param classroomIds 
 * @param id 
 * @param name 
 * @param short 
 * @param teacherId 
 * @param timetableId 
 */
@Serializable

data class GetCohort200ResponseInner (

    @SerialName(value = "classroomIds") @Required val classroomIds: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "short") @Required val short: kotlin.String?,

    @SerialName(value = "teacherId") @Required val teacherId: kotlin.String?,

    @SerialName(value = "timetableId") @Required val timetableId: kotlin.String?

) {


}

