/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebugErrors

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deviceState 
 * @param errors 
 * @param lastResetReason 
 */
@Serializable

data class GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebug (

    @SerialName(value = "deviceState") @Required val deviceState: GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebug.DeviceState,

    @SerialName(value = "errors") @Required val errors: GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebugErrors,

    @SerialName(value = "lastResetReason") @Required val lastResetReason: kotlin.String?

) {

    /**
     * 
     *
     * Values: booting,error,idle,updating
     */
    @Serializable
    enum class DeviceState(val value: kotlin.String) {
        @SerialName(value = "booting") booting("booting"),
        @SerialName(value = "error") error("error"),
        @SerialName(value = "idle") idle("idle"),
        @SerialName(value = "updating") updating("updating");
    }

}

