/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param db 
 * @param nfc 
 * @param ota 
 * @param sd 
 * @param wifi 
 */
@Serializable

data class GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebugErrors (

    @SerialName(value = "db") @Required val db: kotlin.Boolean,

    @SerialName(value = "nfc") @Required val nfc: kotlin.Boolean,

    @SerialName(value = "ota") @Required val ota: kotlin.Boolean,

    @SerialName(value = "sd") @Required val sd: kotlin.Boolean,

    @SerialName(value = "wifi") @Required val wifi: kotlin.Boolean

) {


}

