/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetDoorlockDevices200ResponseDevicesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param devices 
 */
@Serializable

data class GetDoorlockDevices200Response (

    @SerialName(value = "devices") @Required val devices: kotlin.collections.List<GetDoorlockDevices200ResponseDevicesInner>

) {


}

