/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetDoorlockCardsUsers200ResponseUsersInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param users 
 */
@Serializable

data class GetDoorlockCardsUsers200Response (

    @SerialName(value = "users") @Required val users: kotlin.collections.List<GetDoorlockCardsUsers200ResponseUsersInner>

) {


}

