/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMeta

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deviceMeta 
 * @param id 
 * @param timestamp 
 */
@Serializable

data class GetDoorlockDevicesByIdStats200ResponseInner (

    @SerialName(value = "deviceMeta") @Required val deviceMeta: GetDoorlockDevicesByIdStats200ResponseInnerDeviceMeta,

    @SerialName(value = "id") @Required val id: kotlin.Int?,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.String?

) {


}

