/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.Lesson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param success 
 * @param `data` 
 */
@Serializable

data class GetLessonById200Response (

    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "data") val `data`: Lesson? = null

) {


}

