/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buildingId 
 * @param capacity 
 * @param description 
 * @param id 
 * @param mapped 
 * @param name 
 * @param rotation 
 * @param short 
 * @param sizeX 
 * @param sizeY 
 * @param sizeZ 
 * @param storey 
 * @param typeId 
 * @param x 
 * @param y 
 */
@Serializable

data class GetNavigatorClassrooms200ResponseClassroomsInner (

    @SerialName(value = "building_id") @Required val buildingId: kotlin.String?,

    @SerialName(value = "capacity") @Required val capacity: kotlin.Int?,

    @SerialName(value = "description") @Required val description: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "mapped") @Required val mapped: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "rotation") @Required val rotation: kotlin.Double?,

    @SerialName(value = "short") @Required val short: kotlin.String?,

    @SerialName(value = "size_x") @Required val sizeX: kotlin.Double?,

    @SerialName(value = "size_y") @Required val sizeY: kotlin.Double?,

    @SerialName(value = "size_z") @Required val sizeZ: kotlin.Double?,

    @SerialName(value = "storey") @Required val storey: kotlin.Int?,

    @SerialName(value = "type_id") @Required val typeId: kotlin.String?,

    @SerialName(value = "x") @Required val x: kotlin.Double?,

    @SerialName(value = "y") @Required val y: kotlin.Double?

) {


}

