/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNewsAnnouncementsById200ResponseAuthor

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param authorId 
 * @param createdAt 
 * @param id 
 * @param publishedAt 
 * @param slug 
 * @param status 
 * @param title 
 * @param updatedAt 
 * @param content 
 * @param author 
 */
@Serializable

data class GetNewsBlogs200ResponseDataInner (

    @SerialName(value = "authorId") @Required val authorId: kotlin.String?,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "publishedAt") @Required val publishedAt: kotlin.String?,

    @SerialName(value = "slug") @Required val slug: kotlin.String?,

    @SerialName(value = "status") @Required val status: kotlin.String?,

    @SerialName(value = "title") @Required val title: kotlin.String?,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String?,

    @SerialName(value = "content") val content: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "author") val author: GetNewsAnnouncementsById200ResponseAuthor? = null

) {


}

