/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNavigatorCorridors200ResponseCorridorsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param corridors 
 */
@Serializable

data class GetNavigatorCorridors200Response (

    @SerialName(value = "corridors") @Required val corridors: kotlin.collections.List<GetNavigatorCorridors200ResponseCorridorsInner>

) {


}

