/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNavigatorClassrooms200ResponseClassroomsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param classrooms 
 */
@Serializable

data class GetNavigatorClassrooms200Response (

    @SerialName(value = "classrooms") @Required val classrooms: kotlin.collections.List<GetNavigatorClassrooms200ResponseClassroomsInner>

) {


}

