/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNavigatorBuildings200ResponseBuildingsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buildings 
 */
@Serializable

data class GetNavigatorBuildings200Response (

    @SerialName(value = "buildings") @Required val buildings: kotlin.collections.List<GetNavigatorBuildings200ResponseBuildingsInner>

) {


}

