/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNavigatorLifts200ResponseLiftsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lifts 
 */
@Serializable

data class GetNavigatorLifts200Response (

    @SerialName(value = "lifts") @Required val lifts: kotlin.collections.List<GetNavigatorLifts200ResponseLiftsInner>

) {


}

