/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseBuildingsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseClassroomTypesInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseClassroomsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseCorridorsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseLiftsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseStairsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buildings 
 * @param classroomTypes 
 * @param classrooms 
 * @param corridors 
 * @param lifts 
 * @param stairs 
 */
@Serializable

data class GetNavigatorGraph200Response (

    @SerialName(value = "buildings") @Required val buildings: kotlin.collections.List<GetNavigatorGraph200ResponseBuildingsInner>,

    @SerialName(value = "classroom_types") @Required val classroomTypes: kotlin.collections.List<GetNavigatorGraph200ResponseClassroomTypesInner>,

    @SerialName(value = "classrooms") @Required val classrooms: kotlin.collections.List<GetNavigatorGraph200ResponseClassroomsInner>,

    @SerialName(value = "corridors") @Required val corridors: kotlin.collections.List<GetNavigatorGraph200ResponseCorridorsInner>,

    @SerialName(value = "lifts") @Required val lifts: kotlin.collections.List<GetNavigatorGraph200ResponseLiftsInner>,

    @SerialName(value = "stairs") @Required val stairs: kotlin.collections.List<GetNavigatorGraph200ResponseStairsInner>

) {


}

