/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetNewsBlogs200ResponseDataInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param total 
 */
@Serializable

data class GetNewsBlogs200Response (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<GetNewsBlogs200ResponseDataInner>,

    @SerialName(value = "total") @Required val total: kotlin.Double?

) {


}

