/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param pretty 
 * @param uptimeMs 
 */
@Serializable

data class GetPingUptime200Response (

    @SerialName(value = "pretty") @Required val pretty: kotlin.String?,

    @SerialName(value = "uptime_ms") @Required val uptimeMs: kotlin.Double?

) {


}

