/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param divisionLabel 
 * @param divisionTag 
 * @param entireClass 
 * @param id 
 * @param name 
 * @param selected 
 * @param studentCount 
 * @param teacherId 
 */
@Serializable

data class GetTimetableGroupsGetForCohortByCohortId200ResponseInner (

    @SerialName(value = "divisionLabel") @Required val divisionLabel: kotlin.String?,

    @SerialName(value = "divisionTag") @Required val divisionTag: kotlin.String?,

    @SerialName(value = "entireClass") @Required val entireClass: kotlin.Boolean,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "selected") @Required val selected: kotlin.Boolean,

    @SerialName(value = "studentCount") @Required val studentCount: kotlin.Double?,

    @SerialName(value = "teacherId") @Required val teacherId: kotlin.String?

) {


}

