/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param comment 
 * @param date 
 * @param id 
 * @param room 
 * @param startingDay 
 * @param startingPeriod 
 */
@Serializable

data class GetTimetableMovedLessons200ResponseInnerMovedLesson (

    @SerialName(value = "comment") @Required val comment: kotlin.String?,

    @SerialName(value = "date") @Required val date: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "room") @Required val room: kotlin.String?,

    @SerialName(value = "startingDay") @Required val startingDay: kotlin.String?,

    @SerialName(value = "startingPeriod") @Required val startingPeriod: kotlin.String?

) {


}

