/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email 
 * @param id 
 * @param name 
 */
@Serializable

data class GetTimetableTeachers200ResponseInnerUser (

    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?

) {


}

