/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param endTime 
 * @param id 
 * @param period 
 * @param startTime 
 */
@Serializable

data class GetTimetableLessonsGetForCohortByCohortId200ResponseInnerPeriod (

    @SerialName(value = "endTime") @Required val endTime: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "period") @Required val period: kotlin.Double,

    @SerialName(value = "startTime") @Required val startTime: kotlin.String

) {


}

