/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerCohortsInner
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerPeriod
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachers200ResponseInnerLessonsInnerDay

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param classrooms 
 * @param cohorts 
 * @param id 
 * @param period 
 * @param periodsPerWeek 
 * @param subject 
 * @param teachers 
 * @param termDefinitionId 
 * @param weeksDefinitionId 
 * @param day 
 */
@Serializable

data class GetTimetableMovedLessons200ResponseInnerLessonsInner (

    @SerialName(value = "classrooms") @Required val classrooms: kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInnerCohortsInner>,

    @SerialName(value = "cohorts") @Required val cohorts: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "period") @Required val period: GetTimetableLessonsGetForCohortByCohortId200ResponseInnerPeriod?,

    @SerialName(value = "periodsPerWeek") @Required val periodsPerWeek: kotlin.Double,

    @SerialName(value = "subject") @Required val subject: GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject?,

    @SerialName(value = "teachers") @Required val teachers: kotlin.collections.List<GetTimetableLessonsGetForCohortByCohortId200ResponseInnerCohortsInner>,

    @SerialName(value = "termDefinitionId") @Required val termDefinitionId: kotlin.String?,

    @SerialName(value = "weeksDefinitionId") @Required val weeksDefinitionId: kotlin.String,

    @SerialName(value = "day") val day: PostTimetableLessonsGetForTeachers200ResponseInnerLessonsInnerDay? = null

) {


}

