/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetTimetableSubstitutionsRelevant200ResponseInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cohortId 
 * @param substitutions 
 */
@Serializable

data class GetTimetableSubstitutionsCohortByCohortId200Response (

    @SerialName(value = "cohortId") @Required val cohortId: kotlin.String?,

    @SerialName(value = "substitutions") @Required val substitutions: kotlin.collections.List<GetTimetableSubstitutionsRelevant200ResponseInner>

) {


}

