/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerLessonsInner
import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerSubstitution
import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerTeacher

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lessons 
 * @param substitution 
 * @param teacher 
 */
@Serializable

data class GetTimetableSubstitutions200ResponseInner (

    @SerialName(value = "lessons") @Required val lessons: kotlin.collections.List<GetTimetableSubstitutions200ResponseInnerLessonsInner>,

    @SerialName(value = "substitution") @Required val substitution: GetTimetableSubstitutions200ResponseInnerSubstitution,

    @SerialName(value = "teacher") @Required val teacher: GetTimetableSubstitutions200ResponseInnerTeacher?

) {


}

