/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetTimetableTeachers200ResponseInnerUser

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email 
 * @param firstName 
 * @param id 
 * @param lastName 
 * @param short 
 * @param user 
 * @param userId 
 */
@Serializable

data class GetTimetableTeachers200ResponseInner (

    @SerialName(value = "email") @Required val email: kotlin.String?,

    @SerialName(value = "firstName") @Required val firstName: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "lastName") @Required val lastName: kotlin.String?,

    @SerialName(value = "short") @Required val short: kotlin.String?,

    @SerialName(value = "user") @Required val user: GetTimetableTeachers200ResponseInnerUser?,

    @SerialName(value = "userId") @Required val userId: kotlin.String?

) {


}

