/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param danglingUsersCleaned 
 * @param lessonsDeleted 
 * @param movedLessonsDeleted 
 * @param orphanedCohorts 
 * @param substitutionsDeleted 
 * @param survivingCohorts 
 */
@Serializable

data class GetTimetableTimetablesByIdPreviewDelete200ResponseTotals (

    @SerialName(value = "danglingUsersCleaned") @Required val danglingUsersCleaned: kotlin.Double?,

    @SerialName(value = "lessonsDeleted") @Required val lessonsDeleted: kotlin.Double?,

    @SerialName(value = "movedLessonsDeleted") @Required val movedLessonsDeleted: kotlin.Double?,

    @SerialName(value = "orphanedCohorts") @Required val orphanedCohorts: kotlin.Double?,

    @SerialName(value = "substitutionsDeleted") @Required val substitutionsDeleted: kotlin.Double?,

    @SerialName(value = "survivingCohorts") @Required val survivingCohorts: kotlin.Double?

) {


}

