/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param expiresAt 
 * @param id 
 * @param lastUsedAt 
 * @param name 
 * @param prefix 
 * @param updatedAt 
 * @param userId 
 */
@Serializable

data class GetUsersMeApiKeys200ResponseApiKeysInner (

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String?,

    @SerialName(value = "expiresAt") @Required val expiresAt: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "lastUsedAt") @Required val lastUsedAt: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "prefix") @Required val prefix: kotlin.String?,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String?,

    @SerialName(value = "userId") @Required val userId: kotlin.String?

) {


}

