/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cohortId 
 * @param createdAt 
 * @param email 
 * @param emailVerified 
 * @param id 
 * @param image 
 * @param name 
 * @param nickname 
 * @param roles 
 * @param updatedAt 
 * @param displayName 
 * @param permissions 
 */
@Serializable

data class GetUsers200ResponseUsersInner (

    @SerialName(value = "cohortId") @Required val cohortId: kotlin.String?,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.String?,

    @SerialName(value = "email") @Required val email: kotlin.String?,

    @SerialName(value = "emailVerified") @Required val emailVerified: kotlin.Boolean,

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "image") @Required val image: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "nickname") @Required val nickname: kotlin.String?,

    @SerialName(value = "roles") @Required val roles: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.String?,

    @SerialName(value = "displayName") @Required val displayName: kotlin.String?,

    @SerialName(value = "permissions") @Required val permissions: kotlin.collections.List<kotlin.String>

) {


}

