/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetUsersMeApiKeys200ResponseApiKeysInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param apiKeys 
 */
@Serializable

data class GetUsersMeApiKeys200Response (

    @SerialName(value = "apiKeys") @Required val apiKeys: kotlin.collections.List<GetUsersMeApiKeys200ResponseApiKeysInner>

) {


}

