/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cohortId 
 * @param nickname 
 * @param roles 
 */
@Serializable

data class PatchUsersByIdRequest (

    @SerialName(value = "cohortId") val cohortId: kotlin.String? = null,

    @SerialName(value = "nickname") val nickname: kotlin.String? = null,

    @SerialName(value = "roles") val roles: kotlin.collections.List<kotlin.String>? = null

) {


}

