/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PatchNewsAnnouncementsByIdRequestContentInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param content 
 * @param slug 
 * @param title 
 */
@Serializable

data class PatchNewsBlogsByIdRequest (

    @SerialName(value = "content") val content: kotlin.collections.List<PatchNewsAnnouncementsByIdRequestContentInner>? = null,

    @SerialName(value = "slug") val slug: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null

) {


}

