/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param validFrom 
 * @param validTo 
 */
@Serializable

data class PatchTimetableTimetablesByIdRequest (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "validFrom") val validFrom: kotlin.String? = null,

    @SerialName(value = "validTo") val validTo: kotlin.String? = null

) {


}

