/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostKioskDeparturesRequestGroupsInnerStopsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param label 
 * @param stops 
 */
@Serializable

data class PostKioskDeparturesRequestGroupsInner (

    @SerialName(value = "label") @Required val label: kotlin.String?,

    @SerialName(value = "stops") @Required val stops: kotlin.collections.List<PostKioskDeparturesRequestGroupsInnerStopsInner>

) {


}

