/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostNavigatorClassroomTypes201ResponseClassroomType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param classroomType 
 */
@Serializable

data class PostNavigatorClassroomTypes201Response (

    @SerialName(value = "classroom_type") @Required val classroomType: PostNavigatorClassroomTypes201ResponseClassroomType

) {


}

