/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param subject 
 * @param metadata 
 * @param page 
 */
@Serializable

data class PostBugReportRequest (

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "subject") @Required val subject: kotlin.String,

    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

    @SerialName(value = "page") val page: kotlin.String? = null

) {


}

