/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostKioskDepartures200ResponseDeparturesInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param departures 
 */
@Serializable

data class PostKioskDepartures200Response (

    @SerialName(value = "departures") @Required val departures: kotlin.collections.List<PostKioskDepartures200ResponseDeparturesInner>

) {


}

