/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostDoorlockCards201ResponseCard

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param card 
 */
@Serializable

data class PostDoorlockCards201Response (

    @SerialName(value = "card") @Required val card: PostDoorlockCards201ResponseCard

) {


}

