/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.GetTimetableTeachersMe200Response

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param hasH1 
 * @param hasH2 
 * @param teacher 
 */
@Serializable

data class PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInner (

    @SerialName(value = "hasH1") @Required val hasH1: kotlin.Boolean,

    @SerialName(value = "hasH2") @Required val hasH2: kotlin.Boolean,

    @SerialName(value = "teacher") @Required val teacher: GetTimetableTeachersMe200Response?

) {


}

