/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buildings 
 * @param classrooms 
 * @param classroomTypes 
 * @param corridors 
 * @param lifts 
 * @param stairs 
 * @param translations 
 */
@Serializable

data class PostNavigatorImport200Response (

    @SerialName(value = "buildings") @Required val buildings: kotlin.Int?,

    @SerialName(value = "classrooms") @Required val classrooms: kotlin.Int?,

    @SerialName(value = "classroomTypes") @Required val classroomTypes: kotlin.Int?,

    @SerialName(value = "corridors") @Required val corridors: kotlin.Int?,

    @SerialName(value = "lifts") @Required val lifts: kotlin.Int?,

    @SerialName(value = "stairs") @Required val stairs: kotlin.Int?,

    @SerialName(value = "translations") @Required val translations: kotlin.Int?

) {


}

