/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buttonPressed 
 * @param cardData 
 * @param cardId 
 * @param deviceId 
 * @param id 
 * @param result 
 * @param timestamp 
 * @param userId 
 */
@Serializable

data class PostDoorlockSelfCardsByIdActivate200ResponseLog (

    @SerialName(value = "buttonPressed") @Required val buttonPressed: kotlin.Boolean,

    @SerialName(value = "cardData") @Required val cardData: kotlin.String?,

    @SerialName(value = "cardId") @Required val cardId: kotlin.String?,

    @SerialName(value = "deviceId") @Required val deviceId: kotlin.String?,

    @SerialName(value = "id") @Required val id: kotlin.Int?,

    @SerialName(value = "result") @Required val result: kotlin.Boolean,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.String?,

    @SerialName(value = "userId") @Required val userId: kotlin.String?

) {


}

