/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachers200ResponseInnerLessonsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lessons 
 * @param teacherId 
 */
@Serializable

data class PostTimetableLessonsGetForTeachers200ResponseInner (

    @SerialName(value = "lessons") @Required val lessons: kotlin.collections.List<PostTimetableLessonsGetForTeachers200ResponseInnerLessonsInner>,

    @SerialName(value = "teacherId") @Required val teacherId: kotlin.String?

) {


}

