/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf1
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf2
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf2Kiosk

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param registered 
 * @param enabled 
 * @param kiosk 
 */
@Serializable

data class PostKioskHeartbeat200Response (

    @SerialName(value = "registered") @Required val registered: kotlinx.serialization.json.JsonElement?,

    @SerialName(value = "enabled") @Required val enabled: kotlinx.serialization.json.JsonElement?,

    @SerialName(value = "kiosk") @Required val kiosk: PostKioskHeartbeat200ResponseAnyOf2Kiosk

) {


}

