/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param kind 
 * @param machineId 
 * @param name 
 * @param config 
 */
@Serializable

data class PostKioskRequest (

    @SerialName(value = "kind") @Required val kind: PostKioskRequest.Kind,

    @SerialName(value = "machineId") @Required val machineId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "config") val config: kotlinx.serialization.json.JsonElement? = null

) {

    /**
     * 
     *
     * Values: tv,navigator
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "tv") tv("tv"),
        @SerialName(value = "navigator") navigator("navigator");
    }

}

