/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param label 
 * @param predictedDepartureTime 
 * @param routeShortDesc 
 */
@Serializable

data class PostKioskDepartures200ResponseDeparturesInner (

    @SerialName(value = "label") @Required val label: kotlin.String?,

    @SerialName(value = "predictedDepartureTime") @Required val predictedDepartureTime: kotlin.Double?,

    @SerialName(value = "routeShortDesc") @Required val routeShortDesc: kotlin.String?

) {


}

