/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostNavigatorClassrooms201ResponseClassroom

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param classroom 
 */
@Serializable

data class PostNavigatorClassrooms201Response (

    @SerialName(value = "classroom") @Required val classroom: PostNavigatorClassrooms201ResponseClassroom?

) {


}

