/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param comment 
 * @param date 
 * @param id 
 * @param substituter 
 */
@Serializable

data class PostTimetableSubstitutions200Response (

    @SerialName(value = "comment") @Required val comment: kotlin.String?,

    @SerialName(value = "date") @Required val date: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "substituter") @Required val substituter: kotlin.String?

) {


}

