/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param affectedUserCount 
 * @param deletedCohortIds 
 * @param deletedTeacherIds 
 */
@Serializable

data class PostTimetableTimetablesCleanupOrphanedCohorts200Response (

    @SerialName(value = "affectedUserCount") @Required val affectedUserCount: kotlin.Double?,

    @SerialName(value = "deletedCohortIds") @Required val deletedCohortIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "deletedTeacherIds") @Required val deletedTeacherIds: kotlin.collections.List<kotlin.String>

) {


}

