/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param permissions 
 */
@Serializable

data class PostRolesRequest (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "permissions") val permissions: kotlin.collections.List<kotlin.String>? = arrayListOf()

) {


}

