/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import hu.petrik.filcapp.api.model.PostNavigatorTranslations201ResponseTranslationsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param translations 
 */
@Serializable

data class PostNavigatorTranslations201Response (

    @SerialName(value = "translations") @Required val translations: kotlin.collections.List<PostNavigatorTranslations201ResponseTranslationsInner>

) {


}

