/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param apiToken 
 * @param name 
 * @param lastResetReason 
 * @param location 
 */
@Serializable

data class PostDoorlockDevicesRequest (

    @SerialName(value = "apiToken") @Required val apiToken: kotlin.String?,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "lastResetReason") val lastResetReason: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

