/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param kind 
 * @param name 
 */
@Serializable

data class PostKioskHeartbeat200ResponseAnyOf1Kiosk (

    @SerialName(value = "id") @Required val id: kotlin.String?,

    @SerialName(value = "kind") @Required val kind: PostKioskHeartbeat200ResponseAnyOf1Kiosk.Kind,

    @SerialName(value = "name") @Required val name: kotlin.String?

) {

    /**
     * 
     *
     * Values: tv,navigator
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "tv") tv("tv"),
        @SerialName(value = "navigator") navigator("navigator");
    }

}

