/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param userId 
 * @param authorizedDeviceIds 
 * @param enabled 
 * @param frozen 
 */
@Serializable

data class PutDoorlockCardsByIdRequest (

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "userId") @Required val userId: kotlin.String?,

    @SerialName(value = "authorizedDeviceIds") val authorizedDeviceIds: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = true,

    @SerialName(value = "frozen") val frozen: kotlin.Boolean? = false

) {


}

