/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param buildingId 
 * @param capacity 
 * @param description 
 * @param name 
 * @param rotation 
 * @param short 
 * @param sizeX 
 * @param sizeY 
 * @param sizeZ 
 * @param storey 
 * @param typeId 
 * @param x 
 * @param y 
 */
@Serializable

data class PutNavigatorClassroomsByIdRequest (

    @SerialName(value = "building_id") val buildingId: kotlin.String? = null,

    @SerialName(value = "capacity") val capacity: kotlin.Int? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "rotation") val rotation: kotlin.Double? = null,

    @SerialName(value = "short") val short: kotlin.String? = null,

    @SerialName(value = "size_x") val sizeX: kotlin.Double? = null,

    @SerialName(value = "size_y") val sizeY: kotlin.Double? = null,

    @SerialName(value = "size_z") val sizeZ: kotlin.Double? = null,

    @SerialName(value = "storey") val storey: kotlin.Int? = null,

    @SerialName(value = "type_id") val typeId: kotlin.String? = null,

    @SerialName(value = "x") val x: kotlin.Double? = null,

    @SerialName(value = "y") val y: kotlin.Double? = null

) {


}

