/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lessonIds 
 * @param comment 
 * @param date 
 * @param substituter 
 */
@Serializable

data class PutTimetableSubstitutionsByIdRequest (

    @SerialName(value = "lessonIds") @Required val lessonIds: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "date") val date: kotlin.String? = null,

    @SerialName(value = "substituter") val substituter: kotlin.String? = null

) {


}

