/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param date 
 * @param lessonIds 
 * @param room 
 * @param startingDay 
 * @param startingPeriod 
 * @param comment 
 */
@Serializable

data class PutTimetableMovedLessonsByIdRequest (

    @SerialName(value = "date") @Required val date: kotlin.String?,

    @SerialName(value = "lessonIds") @Required val lessonIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "room") @Required val room: kotlin.String?,

    @SerialName(value = "startingDay") @Required val startingDay: kotlin.String?,

    @SerialName(value = "startingPeriod") @Required val startingPeriod: kotlin.String?,

    @SerialName(value = "comment") val comment: kotlin.String? = null

) {


}

