/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetBugReport200Response
import hu.petrik.filcapp.api.model.GetBugReport200ResponseReportsInner

class GetBugReport200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBugReport200Response
        //val modelInstance = GetBugReport200Response()

        // to test the property `reports`
        should("test reports") {
            // uncomment below to test the property
            //modelInstance.reports shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
