/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetCohort200ResponseInner

class GetCohort200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCohort200ResponseInner
        //val modelInstance = GetCohort200ResponseInner()

        // to test the property `classroomIds`
        should("test classroomIds") {
            // uncomment below to test the property
            //modelInstance.classroomIds shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `short`
        should("test short") {
            // uncomment below to test the property
            //modelInstance.short shouldBe ("TODO")
        }

        // to test the property `teacherId`
        should("test teacherId") {
            // uncomment below to test the property
            //modelInstance.teacherId shouldBe ("TODO")
        }

        // to test the property `timetableId`
        should("test timetableId") {
            // uncomment below to test the property
            //modelInstance.timetableId shouldBe ("TODO")
        }

    }
}
