/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebug
import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebugErrors

class GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebugTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebug
        //val modelInstance = GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaDebug()

        // to test the property `deviceState`
        should("test deviceState") {
            // uncomment below to test the property
            //modelInstance.deviceState shouldBe ("TODO")
        }

        // to test the property `errors`
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property `lastResetReason`
        should("test lastResetReason") {
            // uncomment below to test the property
            //modelInstance.lastResetReason shouldBe ("TODO")
        }

    }
}
