/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200ResponseStats
import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200ResponseStatsDoorOpenSeriesInner
import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200ResponseStatsTopUsersInner

class GetDoorlockStatsOverview200ResponseStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockStatsOverview200ResponseStats
        //val modelInstance = GetDoorlockStatsOverview200ResponseStats()

        // to test the property `doorOpenSeries`
        should("test doorOpenSeries") {
            // uncomment below to test the property
            //modelInstance.doorOpenSeries shouldBe ("TODO")
        }

        // to test the property `topUsers`
        should("test topUsers") {
            // uncomment below to test the property
            //modelInstance.topUsers shouldBe ("TODO")
        }

        // to test the property `totalCards`
        should("test totalCards") {
            // uncomment below to test the property
            //modelInstance.totalCards shouldBe ("TODO")
        }

        // to test the property `totalDevices`
        should("test totalDevices") {
            // uncomment below to test the property
            //modelInstance.totalDevices shouldBe ("TODO")
        }

        // to test the property `totalSuccessfulOpens`
        should("test totalSuccessfulOpens") {
            // uncomment below to test the property
            //modelInstance.totalSuccessfulOpens shouldBe ("TODO")
        }

    }
}
