/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInner
import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMeta

class GetDoorlockDevicesByIdStats200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockDevicesByIdStats200ResponseInner
        //val modelInstance = GetDoorlockDevicesByIdStats200ResponseInner()

        // to test the property `deviceMeta`
        should("test deviceMeta") {
            // uncomment below to test the property
            //modelInstance.deviceMeta shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
