/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockLogs200ResponseLogsInner
import hu.petrik.filcapp.api.model.GetDoorlockLogs200ResponseLogsInnerCard
import hu.petrik.filcapp.api.model.PostDoorlockCards201ResponseCardOwner

class GetDoorlockLogs200ResponseLogsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockLogs200ResponseLogsInner
        //val modelInstance = GetDoorlockLogs200ResponseLogsInner()

        // to test the property `buttonPressed`
        should("test buttonPressed") {
            // uncomment below to test the property
            //modelInstance.buttonPressed shouldBe ("TODO")
        }

        // to test the property `cardData`
        should("test cardData") {
            // uncomment below to test the property
            //modelInstance.cardData shouldBe ("TODO")
        }

        // to test the property `cardId`
        should("test cardId") {
            // uncomment below to test the property
            //modelInstance.cardId shouldBe ("TODO")
        }

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `card`
        should("test card") {
            // uncomment below to test the property
            //modelInstance.card shouldBe ("TODO")
        }

        // to test the property `device`
        should("test device") {
            // uncomment below to test the property
            //modelInstance.device shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

    }
}
