/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaStorage

class GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaStorageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaStorage
        //val modelInstance = GetDoorlockDevicesByIdStats200ResponseInnerDeviceMetaStorage()

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `used`
        should("test used") {
            // uncomment below to test the property
            //modelInstance.used shouldBe ("TODO")
        }

    }
}
