/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200ResponseStatsDoorOpenSeriesInner

class GetDoorlockStatsOverview200ResponseStatsDoorOpenSeriesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockStatsOverview200ResponseStatsDoorOpenSeriesInner
        //val modelInstance = GetDoorlockStatsOverview200ResponseStatsDoorOpenSeriesInner()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

    }
}
