/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockDevices200Response
import hu.petrik.filcapp.api.model.GetDoorlockDevices200ResponseDevicesInner

class GetDoorlockDevices200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockDevices200Response
        //val modelInstance = GetDoorlockDevices200Response()

        // to test the property `devices`
        should("test devices") {
            // uncomment below to test the property
            //modelInstance.devices shouldBe ("TODO")
        }

    }
}
