/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockCards200Response
import hu.petrik.filcapp.api.model.GetDoorlockCards200ResponseCardsInner

class GetDoorlockCards200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockCards200Response
        //val modelInstance = GetDoorlockCards200Response()

        // to test the property `cards`
        should("test cards") {
            // uncomment below to test the property
            //modelInstance.cards shouldBe ("TODO")
        }

    }
}
