/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDashboardStats200ResponseStatsChartDataInner

class GetDashboardStats200ResponseStatsChartDataInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDashboardStats200ResponseStatsChartDataInner
        //val modelInstance = GetDashboardStats200ResponseStatsChartDataInner()

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `movedLessons`
        should("test movedLessons") {
            // uncomment below to test the property
            //modelInstance.movedLessons shouldBe ("TODO")
        }

        // to test the property `substitutions`
        should("test substitutions") {
            // uncomment below to test the property
            //modelInstance.substitutions shouldBe ("TODO")
        }

    }
}
