/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200Response
import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200ResponseStats

class GetDoorlockStatsOverview200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockStatsOverview200Response
        //val modelInstance = GetDoorlockStatsOverview200Response()

        // to test the property `stats`
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

    }
}
