/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetDoorlockCardsUsers200Response
import hu.petrik.filcapp.api.model.GetDoorlockCardsUsers200ResponseUsersInner

class GetDoorlockCardsUsers200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDoorlockCardsUsers200Response
        //val modelInstance = GetDoorlockCardsUsers200Response()

        // to test the property `users`
        should("test users") {
            // uncomment below to test the property
            //modelInstance.users shouldBe ("TODO")
        }

    }
}
