/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetKioskPetrikNews200Response
import hu.petrik.filcapp.api.model.GetKioskPetrikNews200ResponseItemsInner

class GetKioskPetrikNews200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetKioskPetrikNews200Response
        //val modelInstance = GetKioskPetrikNews200Response()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
