/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetKioskWeather200Response

class GetKioskWeather200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetKioskWeather200Response
        //val modelInstance = GetKioskWeather200Response()

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

        // to test the property `precipMm`
        should("test precipMm") {
            // uncomment below to test the property
            //modelInstance.precipMm shouldBe ("TODO")
        }

        // to test the property `tempC`
        should("test tempC") {
            // uncomment below to test the property
            //modelInstance.tempC shouldBe ("TODO")
        }

        // to test the property `windKph`
        should("test windKph") {
            // uncomment below to test the property
            //modelInstance.windKph shouldBe ("TODO")
        }

    }
}
