/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetKioskPetrikNews200ResponseItemsInner

class GetKioskPetrikNews200ResponseItemsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetKioskPetrikNews200ResponseItemsInner
        //val modelInstance = GetKioskPetrikNews200ResponseItemsInner()

        // to test the property `body`
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `publishedAt`
        should("test publishedAt") {
            // uncomment below to test the property
            //modelInstance.publishedAt shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
