/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetNavigatorTranslationsAvailable200Response

class GetNavigatorTranslationsAvailable200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetNavigatorTranslationsAvailable200Response
        //val modelInstance = GetNavigatorTranslationsAvailable200Response()

        // to test the property `languages`
        should("test languages") {
            // uncomment below to test the property
            //modelInstance.languages shouldBe ("TODO")
        }

    }
}
