/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetNavigatorClassroomTypes200ResponseClassroomTypesInner

class GetNavigatorClassroomTypes200ResponseClassroomTypesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetNavigatorClassroomTypes200ResponseClassroomTypesInner
        //val modelInstance = GetNavigatorClassroomTypes200ResponseClassroomTypesInner()

        // to test the property `colorhex`
        should("test colorhex") {
            // uncomment below to test the property
            //modelInstance.colorhex shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
