/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseStairsInner

class GetNavigatorGraph200ResponseStairsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetNavigatorGraph200ResponseStairsInner
        //val modelInstance = GetNavigatorGraph200ResponseStairsInner()

        // to test the property `buildingId`
        should("test buildingId") {
            // uncomment below to test the property
            //modelInstance.buildingId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `maxStorey`
        should("test maxStorey") {
            // uncomment below to test the property
            //modelInstance.maxStorey shouldBe ("TODO")
        }

        // to test the property `minStorey`
        should("test minStorey") {
            // uncomment below to test the property
            //modelInstance.minStorey shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `x`
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y`
        should("test y") {
            // uncomment below to test the property
            //modelInstance.y shouldBe ("TODO")
        }

        // to test the property `rotation`
        should("test rotation") {
            // uncomment below to test the property
            //modelInstance.rotation shouldBe ("TODO")
        }

    }
}
