/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetNavigatorLifts200Response
import hu.petrik.filcapp.api.model.GetNavigatorLifts200ResponseLiftsInner

class GetNavigatorLifts200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetNavigatorLifts200Response
        //val modelInstance = GetNavigatorLifts200Response()

        // to test the property `lifts`
        should("test lifts") {
            // uncomment below to test the property
            //modelInstance.lifts shouldBe ("TODO")
        }

    }
}
