/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetNavigatorGraph200Response
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseBuildingsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseClassroomTypesInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseClassroomsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseCorridorsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseLiftsInner
import hu.petrik.filcapp.api.model.GetNavigatorGraph200ResponseStairsInner

class GetNavigatorGraph200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetNavigatorGraph200Response
        //val modelInstance = GetNavigatorGraph200Response()

        // to test the property `buildings`
        should("test buildings") {
            // uncomment below to test the property
            //modelInstance.buildings shouldBe ("TODO")
        }

        // to test the property `classroomTypes`
        should("test classroomTypes") {
            // uncomment below to test the property
            //modelInstance.classroomTypes shouldBe ("TODO")
        }

        // to test the property `classrooms`
        should("test classrooms") {
            // uncomment below to test the property
            //modelInstance.classrooms shouldBe ("TODO")
        }

        // to test the property `corridors`
        should("test corridors") {
            // uncomment below to test the property
            //modelInstance.corridors shouldBe ("TODO")
        }

        // to test the property `lifts`
        should("test lifts") {
            // uncomment below to test the property
            //modelInstance.lifts shouldBe ("TODO")
        }

        // to test the property `stairs`
        should("test stairs") {
            // uncomment below to test the property
            //modelInstance.stairs shouldBe ("TODO")
        }

    }
}
