/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetPingUptime200Response

class GetPingUptime200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetPingUptime200Response
        //val modelInstance = GetPingUptime200Response()

        // to test the property `pretty`
        should("test pretty") {
            // uncomment below to test the property
            //modelInstance.pretty shouldBe ("TODO")
        }

        // to test the property `uptimeMs`
        should("test uptimeMs") {
            // uncomment below to test the property
            //modelInstance.uptimeMs shouldBe ("TODO")
        }

    }
}
