/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetRoles200Response
import hu.petrik.filcapp.api.model.GetRoles200ResponseRolesInner

class GetRoles200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRoles200Response
        //val modelInstance = GetRoles200Response()

        // to test the property `roles`
        should("test roles") {
            // uncomment below to test the property
            //modelInstance.roles shouldBe ("TODO")
        }

    }
}
