/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableSubstitutionsCohortByCohortId200Response
import hu.petrik.filcapp.api.model.GetTimetableSubstitutionsRelevant200ResponseInner

class GetTimetableSubstitutionsCohortByCohortId200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableSubstitutionsCohortByCohortId200Response
        //val modelInstance = GetTimetableSubstitutionsCohortByCohortId200Response()

        // to test the property `cohortId`
        should("test cohortId") {
            // uncomment below to test the property
            //modelInstance.cohortId shouldBe ("TODO")
        }

        // to test the property `substitutions`
        should("test substitutions") {
            // uncomment below to test the property
            //modelInstance.substitutions shouldBe ("TODO")
        }

    }
}
