/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableTimetablesByIdPreviewDelete200Response
import hu.petrik.filcapp.api.model.GetTimetableTimetablesByIdPreviewDelete200ResponseCohortsInner
import hu.petrik.filcapp.api.model.GetTimetableTimetablesByIdPreviewDelete200ResponseTargetTimetable
import hu.petrik.filcapp.api.model.GetTimetableTimetablesByIdPreviewDelete200ResponseTotals

class GetTimetableTimetablesByIdPreviewDelete200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableTimetablesByIdPreviewDelete200Response
        //val modelInstance = GetTimetableTimetablesByIdPreviewDelete200Response()

        // to test the property `cohorts`
        should("test cohorts") {
            // uncomment below to test the property
            //modelInstance.cohorts shouldBe ("TODO")
        }

        // to test the property `isCurrentTimetable`
        should("test isCurrentTimetable") {
            // uncomment below to test the property
            //modelInstance.isCurrentTimetable shouldBe ("TODO")
        }

        // to test the property `targetTimetable`
        should("test targetTimetable") {
            // uncomment below to test the property
            //modelInstance.targetTimetable shouldBe ("TODO")
        }

        // to test the property `totals`
        should("test totals") {
            // uncomment below to test the property
            //modelInstance.totals shouldBe ("TODO")
        }

    }
}
