/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableTimetablesByIdPreviewDelete200ResponseTotals

class GetTimetableTimetablesByIdPreviewDelete200ResponseTotalsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableTimetablesByIdPreviewDelete200ResponseTotals
        //val modelInstance = GetTimetableTimetablesByIdPreviewDelete200ResponseTotals()

        // to test the property `danglingUsersCleaned`
        should("test danglingUsersCleaned") {
            // uncomment below to test the property
            //modelInstance.danglingUsersCleaned shouldBe ("TODO")
        }

        // to test the property `lessonsDeleted`
        should("test lessonsDeleted") {
            // uncomment below to test the property
            //modelInstance.lessonsDeleted shouldBe ("TODO")
        }

        // to test the property `movedLessonsDeleted`
        should("test movedLessonsDeleted") {
            // uncomment below to test the property
            //modelInstance.movedLessonsDeleted shouldBe ("TODO")
        }

        // to test the property `orphanedCohorts`
        should("test orphanedCohorts") {
            // uncomment below to test the property
            //modelInstance.orphanedCohorts shouldBe ("TODO")
        }

        // to test the property `substitutionsDeleted`
        should("test substitutionsDeleted") {
            // uncomment below to test the property
            //modelInstance.substitutionsDeleted shouldBe ("TODO")
        }

        // to test the property `survivingCohorts`
        should("test survivingCohorts") {
            // uncomment below to test the property
            //modelInstance.survivingCohorts shouldBe ("TODO")
        }

    }
}
