/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerSubstitution

class GetTimetableSubstitutions200ResponseInnerSubstitutionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableSubstitutions200ResponseInnerSubstitution
        //val modelInstance = GetTimetableSubstitutions200ResponseInnerSubstitution()

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `substituter`
        should("test substituter") {
            // uncomment below to test the property
            //modelInstance.substituter shouldBe ("TODO")
        }

    }
}
