/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForIdByLessonId200ResponseGroupsInner

class GetTimetableLessonsGetForIdByLessonId200ResponseGroupsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableLessonsGetForIdByLessonId200ResponseGroupsInner
        //val modelInstance = GetTimetableLessonsGetForIdByLessonId200ResponseGroupsInner()

        // to test the property `divisionTag`
        should("test divisionTag") {
            // uncomment below to test the property
            //modelInstance.divisionTag shouldBe ("TODO")
        }

        // to test the property `entireClass`
        should("test entireClass") {
            // uncomment below to test the property
            //modelInstance.entireClass shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
