/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject

class GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject
        //val modelInstance = GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `short`
        should("test short") {
            // uncomment below to test the property
            //modelInstance.short shouldBe ("TODO")
        }

    }
}
