/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInnerClassroom
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInnerDayDefinition
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInnerMovedLesson
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInnerPeriod
import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerLessonsInner

class GetTimetableMovedLessons200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableMovedLessons200ResponseInner
        //val modelInstance = GetTimetableMovedLessons200ResponseInner()

        // to test the property `classroom`
        should("test classroom") {
            // uncomment below to test the property
            //modelInstance.classroom shouldBe ("TODO")
        }

        // to test the property `dayDefinition`
        should("test dayDefinition") {
            // uncomment below to test the property
            //modelInstance.dayDefinition shouldBe ("TODO")
        }

        // to test the property `lessons`
        should("test lessons") {
            // uncomment below to test the property
            //modelInstance.lessons shouldBe ("TODO")
        }

        // to test the property `movedLesson`
        should("test movedLesson") {
            // uncomment below to test the property
            //modelInstance.movedLesson shouldBe ("TODO")
        }

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

    }
}
