/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerClassroomsInner
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerDay
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerGroupsInner
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerPeriod
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerSubject
import hu.petrik.filcapp.api.model.GetTimetableLessonsGetForCohortByCohortId200ResponseInnerWeekDefinition

class GetTimetableLessonsGetForCohortByCohortId200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTimetableLessonsGetForCohortByCohortId200ResponseInner
        //val modelInstance = GetTimetableLessonsGetForCohortByCohortId200ResponseInner()

        // to test the property `classrooms`
        should("test classrooms") {
            // uncomment below to test the property
            //modelInstance.classrooms shouldBe ("TODO")
        }

        // to test the property `cohorts`
        should("test cohorts") {
            // uncomment below to test the property
            //modelInstance.cohorts shouldBe ("TODO")
        }

        // to test the property `groups`
        should("test groups") {
            // uncomment below to test the property
            //modelInstance.groups shouldBe ("TODO")
        }

        // to test the property `groupsIds`
        should("test groupsIds") {
            // uncomment below to test the property
            //modelInstance.groupsIds shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `periodsPerWeek`
        should("test periodsPerWeek") {
            // uncomment below to test the property
            //modelInstance.periodsPerWeek shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `teachers`
        should("test teachers") {
            // uncomment below to test the property
            //modelInstance.teachers shouldBe ("TODO")
        }

        // to test the property `termDefinitionId`
        should("test termDefinitionId") {
            // uncomment below to test the property
            //modelInstance.termDefinitionId shouldBe ("TODO")
        }

        // to test the property `weekDefinition`
        should("test weekDefinition") {
            // uncomment below to test the property
            //modelInstance.weekDefinition shouldBe ("TODO")
        }

        // to test the property `weeksDefinitionId`
        should("test weeksDefinitionId") {
            // uncomment below to test the property
            //modelInstance.weeksDefinitionId shouldBe ("TODO")
        }

        // to test the property `day`
        should("test day") {
            // uncomment below to test the property
            //modelInstance.day shouldBe ("TODO")
        }

    }
}
