/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.MovedLesson
import hu.petrik.filcapp.api.model.Lesson

class MovedLessonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovedLesson
        //val modelInstance = MovedLesson()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `originalDate`
        should("test originalDate") {
            // uncomment below to test the property
            //modelInstance.originalDate shouldBe ("TODO")
        }

        // to test the property `newDate`
        should("test newDate") {
            // uncomment below to test the property
            //modelInstance.newDate shouldBe ("TODO")
        }

        // to test the property `lessonId`
        should("test lessonId") {
            // uncomment below to test the property
            //modelInstance.lessonId shouldBe ("TODO")
        }

        // to test the property `lesson`
        should("test lesson") {
            // uncomment below to test the property
            //modelInstance.lesson shouldBe ("TODO")
        }

    }
}
