/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PatchNewsSystemMessagesByIdRequest
import hu.petrik.filcapp.api.model.PostNewsAnnouncementsRequestContentInner

class PatchNewsSystemMessagesByIdRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatchNewsSystemMessagesByIdRequest
        //val modelInstance = PatchNewsSystemMessagesByIdRequest()

        // to test the property `cohortIds`
        should("test cohortIds") {
            // uncomment below to test the property
            //modelInstance.cohortIds shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `validFrom`
        should("test validFrom") {
            // uncomment below to test the property
            //modelInstance.validFrom shouldBe ("TODO")
        }

        // to test the property `validUntil`
        should("test validUntil") {
            // uncomment below to test the property
            //modelInstance.validUntil shouldBe ("TODO")
        }

    }
}
