/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PatchNewsAnnouncementsByIdRequestContentInner

class PatchNewsAnnouncementsByIdRequestContentInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatchNewsAnnouncementsByIdRequestContentInner
        //val modelInstance = PatchNewsAnnouncementsByIdRequestContentInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

    }
}
