/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostNavigatorClassrooms201Response
import hu.petrik.filcapp.api.model.PostNavigatorClassrooms201ResponseClassroom

class PostNavigatorClassrooms201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostNavigatorClassrooms201Response
        //val modelInstance = PostNavigatorClassrooms201Response()

        // to test the property `classroom`
        should("test classroom") {
            // uncomment below to test the property
            //modelInstance.classroom shouldBe ("TODO")
        }

    }
}
