/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostTimetableLessonsGetSubstitutionCandidates200Response
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachers200ResponseInnerLessonsInner
import hu.petrik.filcapp.api.model.PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInner

class PostTimetableLessonsGetSubstitutionCandidates200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostTimetableLessonsGetSubstitutionCandidates200Response
        //val modelInstance = PostTimetableLessonsGetSubstitutionCandidates200Response()

        // to test the property `availableLessons`
        should("test availableLessons") {
            // uncomment below to test the property
            //modelInstance.availableLessons shouldBe ("TODO")
        }

        // to test the property `parallelLessons`
        should("test parallelLessons") {
            // uncomment below to test the property
            //modelInstance.parallelLessons shouldBe ("TODO")
        }

        // to test the property `substituteCandidates`
        should("test substituteCandidates") {
            // uncomment below to test the property
            //modelInstance.substituteCandidates shouldBe ("TODO")
        }

    }
}
