/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostBugReport400Response

class PostBugReport400ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostBugReport400Response
        //val modelInstance = PostBugReport400Response()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
