/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskDeparturesRequest
import hu.petrik.filcapp.api.model.PostKioskDeparturesRequestGroupsInner

class PostKioskDeparturesRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskDeparturesRequest
        //val modelInstance = PostKioskDeparturesRequest()

        // to test the property `groups`
        should("test groups") {
            // uncomment below to test the property
            //modelInstance.groups shouldBe ("TODO")
        }

    }
}
