/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskDepartures200ResponseDeparturesInner

class PostKioskDepartures200ResponseDeparturesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskDepartures200ResponseDeparturesInner
        //val modelInstance = PostKioskDepartures200ResponseDeparturesInner()

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `predictedDepartureTime`
        should("test predictedDepartureTime") {
            // uncomment below to test the property
            //modelInstance.predictedDepartureTime shouldBe ("TODO")
        }

        // to test the property `routeShortDesc`
        should("test routeShortDesc") {
            // uncomment below to test the property
            //modelInstance.routeShortDesc shouldBe ("TODO")
        }

    }
}
