/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostNavigatorLifts201Response
import hu.petrik.filcapp.api.model.PostNavigatorLifts201ResponseLift

class PostNavigatorLifts201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostNavigatorLifts201Response
        //val modelInstance = PostNavigatorLifts201Response()

        // to test the property `lift`
        should("test lift") {
            // uncomment below to test the property
            //modelInstance.lift shouldBe ("TODO")
        }

    }
}
