/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostNavigatorClassroomTypes201Response
import hu.petrik.filcapp.api.model.PostNavigatorClassroomTypes201ResponseClassroomType

class PostNavigatorClassroomTypes201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostNavigatorClassroomTypes201Response
        //val modelInstance = PostNavigatorClassroomTypes201Response()

        // to test the property `classroomType`
        should("test classroomType") {
            // uncomment below to test the property
            //modelInstance.classroomType shouldBe ("TODO")
        }

    }
}
