/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostDoorlockCards201ResponseCard
import hu.petrik.filcapp.api.model.PostDoorlockCards201ResponseCardAuthorizedDevicesInner
import hu.petrik.filcapp.api.model.PostDoorlockCards201ResponseCardOwner

class PostDoorlockCards201ResponseCardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostDoorlockCards201ResponseCard
        //val modelInstance = PostDoorlockCards201ResponseCard()

        // to test the property `authorizedDevices`
        should("test authorizedDevices") {
            // uncomment below to test the property
            //modelInstance.authorizedDevices shouldBe ("TODO")
        }

        // to test the property `cardData`
        should("test cardData") {
            // uncomment below to test the property
            //modelInstance.cardData shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `frozen`
        should("test frozen") {
            // uncomment below to test the property
            //modelInstance.frozen shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `owner`
        should("test owner") {
            // uncomment below to test the property
            //modelInstance.owner shouldBe ("TODO")
        }

    }
}
