/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostDoorlockSelfCardsByIdActivate200Response
import hu.petrik.filcapp.api.model.PostDoorlockSelfCardsByIdActivate200ResponseLog

class PostDoorlockSelfCardsByIdActivate200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostDoorlockSelfCardsByIdActivate200Response
        //val modelInstance = PostDoorlockSelfCardsByIdActivate200Response()

        // to test the property `log`
        should("test log") {
            // uncomment below to test the property
            //modelInstance.log shouldBe ("TODO")
        }

    }
}
