/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostDoorlockSelfCardsByIdActivateRequest

class PostDoorlockSelfCardsByIdActivateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostDoorlockSelfCardsByIdActivateRequest
        //val modelInstance = PostDoorlockSelfCardsByIdActivateRequest()

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

    }
}
