/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdateRequest

class PostDoorlockDevicesByIdUpdateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostDoorlockDevicesByIdUpdateRequest
        //val modelInstance = PostDoorlockDevicesByIdUpdateRequest()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
