/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskDeparturesRequestGroupsInner
import hu.petrik.filcapp.api.model.PostKioskDeparturesRequestGroupsInnerStopsInner

class PostKioskDeparturesRequestGroupsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskDeparturesRequestGroupsInner
        //val modelInstance = PostKioskDeparturesRequestGroupsInner()

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `stops`
        should("test stops") {
            // uncomment below to test the property
            //modelInstance.stops shouldBe ("TODO")
        }

    }
}
