/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskDepartures200Response
import hu.petrik.filcapp.api.model.PostKioskDepartures200ResponseDeparturesInner

class PostKioskDepartures200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskDepartures200Response
        //val modelInstance = PostKioskDepartures200Response()

        // to test the property `departures`
        should("test departures") {
            // uncomment below to test the property
            //modelInstance.departures shouldBe ("TODO")
        }

    }
}
