/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskHeartbeatRequest

class PostKioskHeartbeatRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskHeartbeatRequest
        //val modelInstance = PostKioskHeartbeatRequest()

        // to test the property `appVersion`
        should("test appVersion") {
            // uncomment below to test the property
            //modelInstance.appVersion shouldBe ("TODO")
        }

        // to test the property `machineId`
        should("test machineId") {
            // uncomment below to test the property
            //modelInstance.machineId shouldBe ("TODO")
        }

    }
}
