/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskDeparturesRequestGroupsInnerStopsInner

class PostKioskDeparturesRequestGroupsInnerStopsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskDeparturesRequestGroupsInnerStopsInner
        //val modelInstance = PostKioskDeparturesRequestGroupsInnerStopsInner()

        // to test the property `stopId`
        should("test stopId") {
            // uncomment below to test the property
            //modelInstance.stopId shouldBe ("TODO")
        }

        // to test the property `routeFilter`
        should("test routeFilter") {
            // uncomment below to test the property
            //modelInstance.routeFilter shouldBe ("TODO")
        }

    }
}
