/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostTimetableLessonsGetForTeachersRequest

class PostTimetableLessonsGetForTeachersRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostTimetableLessonsGetForTeachersRequest
        //val modelInstance = PostTimetableLessonsGetForTeachersRequest()

        // to test the property `teacherIds`
        should("test teacherIds") {
            // uncomment below to test the property
            //modelInstance.teacherIds shouldBe ("TODO")
        }

    }
}
