/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdate200Response

class PostDoorlockDevicesByIdUpdate200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostDoorlockDevicesByIdUpdate200Response
        //val modelInstance = PostDoorlockDevicesByIdUpdate200Response()

        // to test the property `ok`
        should("test ok") {
            // uncomment below to test the property
            //modelInstance.ok shouldBe ("TODO")
        }

    }
}
