/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostNewsSystemMessages201Response

class PostNewsSystemMessages201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostNewsSystemMessages201Response
        //val modelInstance = PostNewsSystemMessages201Response()

        // to test the property `authorId`
        should("test authorId") {
            // uncomment below to test the property
            //modelInstance.authorId shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `validFrom`
        should("test validFrom") {
            // uncomment below to test the property
            //modelInstance.validFrom shouldBe ("TODO")
        }

        // to test the property `validUntil`
        should("test validUntil") {
            // uncomment below to test the property
            //modelInstance.validUntil shouldBe ("TODO")
        }

        // to test the property `cohortIds`
        should("test cohortIds") {
            // uncomment below to test the property
            //modelInstance.cohortIds shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

    }
}
