/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf

class PostKioskHeartbeat200ResponseAnyOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskHeartbeat200ResponseAnyOf
        //val modelInstance = PostKioskHeartbeat200ResponseAnyOf()

        // to test the property `registered`
        should("test registered") {
            // uncomment below to test the property
            //modelInstance.registered shouldBe ("TODO")
        }

    }
}
