/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostNavigatorTranslations201Response
import hu.petrik.filcapp.api.model.PostNavigatorTranslations201ResponseTranslationsInner

class PostNavigatorTranslations201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostNavigatorTranslations201Response
        //val modelInstance = PostNavigatorTranslations201Response()

        // to test the property `translations`
        should("test translations") {
            // uncomment below to test the property
            //modelInstance.translations shouldBe ("TODO")
        }

    }
}
