/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostTimetableMovedLessonsRequest

class PostTimetableMovedLessonsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostTimetableMovedLessonsRequest
        //val modelInstance = PostTimetableMovedLessonsRequest()

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `lessonIds`
        should("test lessonIds") {
            // uncomment below to test the property
            //modelInstance.lessonIds shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `room`
        should("test room") {
            // uncomment below to test the property
            //modelInstance.room shouldBe ("TODO")
        }

        // to test the property `startingDay`
        should("test startingDay") {
            // uncomment below to test the property
            //modelInstance.startingDay shouldBe ("TODO")
        }

        // to test the property `startingPeriod`
        should("test startingPeriod") {
            // uncomment below to test the property
            //modelInstance.startingPeriod shouldBe ("TODO")
        }

    }
}
