/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf1
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200ResponseAnyOf1Kiosk

class PostKioskHeartbeat200ResponseAnyOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostKioskHeartbeat200ResponseAnyOf1
        //val modelInstance = PostKioskHeartbeat200ResponseAnyOf1()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `kiosk`
        should("test kiosk") {
            // uncomment below to test the property
            //modelInstance.kiosk shouldBe ("TODO")
        }

        // to test the property `registered`
        should("test registered") {
            // uncomment below to test the property
            //modelInstance.registered shouldBe ("TODO")
        }

    }
}
