/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInner
import hu.petrik.filcapp.api.model.GetTimetableTeachersMe200Response

class PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInner
        //val modelInstance = PostTimetableLessonsGetSubstitutionCandidates200ResponseSubstituteCandidatesInner()

        // to test the property `hasH1`
        should("test hasH1") {
            // uncomment below to test the property
            //modelInstance.hasH1 shouldBe ("TODO")
        }

        // to test the property `hasH2`
        should("test hasH2") {
            // uncomment below to test the property
            //modelInstance.hasH2 shouldBe ("TODO")
        }

        // to test the property `teacher`
        should("test teacher") {
            // uncomment below to test the property
            //modelInstance.teacher shouldBe ("TODO")
        }

    }
}
