/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.PutDoorlockSelfCardsByIdFrozenRequest

class PutDoorlockSelfCardsByIdFrozenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutDoorlockSelfCardsByIdFrozenRequest
        //val modelInstance = PutDoorlockSelfCardsByIdFrozenRequest()

        // to test the property `frozen`
        should("test frozen") {
            // uncomment below to test the property
            //modelInstance.frozen shouldBe ("TODO")
        }

    }
}
