/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.model.Substitution
import hu.petrik.filcapp.api.model.Classroom
import hu.petrik.filcapp.api.model.Lesson
import hu.petrik.filcapp.api.model.Teacher

class SubstitutionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Substitution
        //val modelInstance = Substitution()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `lessonId`
        should("test lessonId") {
            // uncomment below to test the property
            //modelInstance.lessonId shouldBe ("TODO")
        }

        // to test the property `substituteTeacherId`
        should("test substituteTeacherId") {
            // uncomment below to test the property
            //modelInstance.substituteTeacherId shouldBe ("TODO")
        }

        // to test the property `classroomId`
        should("test classroomId") {
            // uncomment below to test the property
            //modelInstance.classroomId shouldBe ("TODO")
        }

        // to test the property `cohortId`
        should("test cohortId") {
            // uncomment below to test the property
            //modelInstance.cohortId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `lesson`
        should("test lesson") {
            // uncomment below to test the property
            //modelInstance.lesson shouldBe ("TODO")
        }

        // to test the property `substituteTeacher`
        should("test substituteTeacher") {
            // uncomment below to test the property
            //modelInstance.substituteTeacher shouldBe ("TODO")
        }

        // to test the property `classroom`
        should("test classroom") {
            // uncomment below to test the property
            //modelInstance.classroom shouldBe ("TODO")
        }

    }
}
