/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.BugReportsApi
import hu.petrik.filcapp.api.model.DeleteBugReportById200Response
import hu.petrik.filcapp.api.model.GetBugReport200Response
import hu.petrik.filcapp.api.model.GetBugReport400Response
import hu.petrik.filcapp.api.model.PatchBugReportByIdStatus200Response
import hu.petrik.filcapp.api.model.PatchBugReportByIdStatusRequest
import hu.petrik.filcapp.api.model.PostBugReport201Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostBugReportRequest

class BugReportsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BugReportsApi
        //val apiInstance = BugReportsApi()

        // to test deleteBugReportById
        should("test deleteBugReportById") {
            // uncomment below to test deleteBugReportById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : DeleteBugReportById200Response = apiInstance.deleteBugReportById(id)
            //result shouldBe ("TODO")
        }

        // to test getBugReport
        should("test getBugReport") {
            // uncomment below to test getBugReport
            //val dateFrom : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val dateTo : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val status : kotlin.String = status_example // kotlin.String | 
            //val result : GetBugReport200Response = apiInstance.getBugReport(dateFrom, dateTo, limit, page, search, status)
            //result shouldBe ("TODO")
        }

        // to test patchBugReportByIdStatus
        should("test patchBugReportByIdStatus") {
            // uncomment below to test patchBugReportByIdStatus
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val patchBugReportByIdStatusRequest : PatchBugReportByIdStatusRequest =  // PatchBugReportByIdStatusRequest | 
            //val result : PatchBugReportByIdStatus200Response = apiInstance.patchBugReportByIdStatus(id, patchBugReportByIdStatusRequest)
            //result shouldBe ("TODO")
        }

        // to test postBugReport
        should("test postBugReport") {
            // uncomment below to test postBugReport
            //val postBugReportRequest : PostBugReportRequest =  // PostBugReportRequest | 
            //val result : PostBugReport201Response = apiInstance.postBugReport(postBugReportRequest)
            //result shouldBe ("TODO")
        }

    }
}
