/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.ClassroomApi
import hu.petrik.filcapp.api.model.GetTimetableClassroomsGetAll200ResponseInner

class ClassroomApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ClassroomApi
        //val apiInstance = ClassroomApi()

        // to test getTimetableClassroomsGetAll
        should("test getTimetableClassroomsGetAll") {
            // uncomment below to test getTimetableClassroomsGetAll
            //val result : kotlin.collections.List<GetTimetableClassroomsGetAll200ResponseInner> = apiInstance.getTimetableClassroomsGetAll()
            //result shouldBe ("TODO")
        }

    }
}
