/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.CohortApi
import hu.petrik.filcapp.api.model.ErrorResponse
import hu.petrik.filcapp.api.model.GetCohortsForTimetable200Response

class CohortApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CohortApi
        //val apiInstance = CohortApi()

        // to test getCohorts
        should("test getCohorts") {
            // uncomment below to test getCohorts
            //val result : GetCohortsForTimetable200Response = apiInstance.getCohorts()
            //result shouldBe ("TODO")
        }

    }
}
