/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.DashboardApi
import hu.petrik.filcapp.api.model.GetDashboardStats200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response

class DashboardApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DashboardApi
        //val apiInstance = DashboardApi()

        // to test getDashboardStats
        should("test getDashboardStats") {
            // uncomment below to test getDashboardStats
            //val days : kotlin.Int = 56 // kotlin.Int | 
            //val result : GetDashboardStats200Response = apiInstance.getDashboardStats(days)
            //result shouldBe ("TODO")
        }

    }
}
