/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.DoorlockApi
import hu.petrik.filcapp.api.model.DeleteBugReportById200Response
import hu.petrik.filcapp.api.model.GetDoorlockCards200Response
import hu.petrik.filcapp.api.model.GetDoorlockCardsUsers200Response
import hu.petrik.filcapp.api.model.GetDoorlockDevices200Response
import hu.petrik.filcapp.api.model.GetDoorlockDevicesByIdStats200ResponseInner
import hu.petrik.filcapp.api.model.GetDoorlockLogs200Response
import hu.petrik.filcapp.api.model.GetDoorlockStatsOverview200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostDoorlockCards201Response
import hu.petrik.filcapp.api.model.PostDoorlockCardsRequest
import hu.petrik.filcapp.api.model.PostDoorlockDevices201Response
import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdate200Response
import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdateRequest
import hu.petrik.filcapp.api.model.PostDoorlockDevicesRequest
import hu.petrik.filcapp.api.model.PostDoorlockDevicesUpdate200Response
import hu.petrik.filcapp.api.model.PostDoorlockSelfCardsByIdActivate200Response
import hu.petrik.filcapp.api.model.PostDoorlockSelfCardsByIdActivateRequest
import hu.petrik.filcapp.api.model.PutDoorlockCardsByIdRequest
import hu.petrik.filcapp.api.model.PutDoorlockDevicesByIdRequest
import hu.petrik.filcapp.api.model.PutDoorlockSelfCardsByIdFrozenRequest

class DoorlockApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DoorlockApi
        //val apiInstance = DoorlockApi()

        // to test deleteDoorlockCardsById
        should("test deleteDoorlockCardsById") {
            // uncomment below to test deleteDoorlockCardsById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : DeleteBugReportById200Response = apiInstance.deleteDoorlockCardsById(id)
            //result shouldBe ("TODO")
        }

        // to test deleteDoorlockDevicesById
        should("test deleteDoorlockDevicesById") {
            // uncomment below to test deleteDoorlockDevicesById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : DeleteBugReportById200Response = apiInstance.deleteDoorlockDevicesById(id)
            //result shouldBe ("TODO")
        }

        // to test getDoorlockCards
        should("test getDoorlockCards") {
            // uncomment below to test getDoorlockCards
            //val result : GetDoorlockCards200Response = apiInstance.getDoorlockCards()
            //result shouldBe ("TODO")
        }

        // to test getDoorlockCardsUsers
        should("test getDoorlockCardsUsers") {
            // uncomment below to test getDoorlockCardsUsers
            //val result : GetDoorlockCardsUsers200Response = apiInstance.getDoorlockCardsUsers()
            //result shouldBe ("TODO")
        }

        // to test getDoorlockDevices
        should("test getDoorlockDevices") {
            // uncomment below to test getDoorlockDevices
            //val result : GetDoorlockDevices200Response = apiInstance.getDoorlockDevices()
            //result shouldBe ("TODO")
        }

        // to test getDoorlockDevicesByIdStats
        should("test getDoorlockDevicesByIdStats") {
            // uncomment below to test getDoorlockDevicesByIdStats
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : kotlin.collections.List<GetDoorlockDevicesByIdStats200ResponseInner> = apiInstance.getDoorlockDevicesByIdStats(id)
            //result shouldBe ("TODO")
        }

        // to test getDoorlockLogs
        should("test getDoorlockLogs") {
            // uncomment below to test getDoorlockLogs
            //val cardId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val deviceId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val from : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val granted : kotlin.String = granted_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val to : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val userId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : GetDoorlockLogs200Response = apiInstance.getDoorlockLogs(cardId, deviceId, from, granted, limit, search, to, userId)
            //result shouldBe ("TODO")
        }

        // to test getDoorlockLogsExport
        should("test getDoorlockLogsExport") {
            // uncomment below to test getDoorlockLogsExport
            //val cardId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val deviceId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val from : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val granted : kotlin.String = granted_example // kotlin.String | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val to : kotlin.String = 2013-10-20T19:20:30+01:00 // kotlin.String | 
            //val userId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : kotlin.String = apiInstance.getDoorlockLogsExport(cardId, deviceId, from, granted, search, to, userId)
            //result shouldBe ("TODO")
        }

        // to test getDoorlockSelfCards
        should("test getDoorlockSelfCards") {
            // uncomment below to test getDoorlockSelfCards
            //val result : GetDoorlockCards200Response = apiInstance.getDoorlockSelfCards()
            //result shouldBe ("TODO")
        }

        // to test getDoorlockStatsOverview
        should("test getDoorlockStatsOverview") {
            // uncomment below to test getDoorlockStatsOverview
            //val result : GetDoorlockStatsOverview200Response = apiInstance.getDoorlockStatsOverview()
            //result shouldBe ("TODO")
        }

        // to test postDoorlockCards
        should("test postDoorlockCards") {
            // uncomment below to test postDoorlockCards
            //val postDoorlockCardsRequest : PostDoorlockCardsRequest =  // PostDoorlockCardsRequest | 
            //val result : PostDoorlockCards201Response = apiInstance.postDoorlockCards(postDoorlockCardsRequest)
            //result shouldBe ("TODO")
        }

        // to test postDoorlockDevices
        should("test postDoorlockDevices") {
            // uncomment below to test postDoorlockDevices
            //val postDoorlockDevicesRequest : PostDoorlockDevicesRequest =  // PostDoorlockDevicesRequest | 
            //val result : PostDoorlockDevices201Response = apiInstance.postDoorlockDevices(postDoorlockDevicesRequest)
            //result shouldBe ("TODO")
        }

        // to test postDoorlockDevicesByIdUpdate
        should("test postDoorlockDevicesByIdUpdate") {
            // uncomment below to test postDoorlockDevicesByIdUpdate
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val postDoorlockDevicesByIdUpdateRequest : PostDoorlockDevicesByIdUpdateRequest =  // PostDoorlockDevicesByIdUpdateRequest | 
            //val result : PostDoorlockDevicesByIdUpdate200Response = apiInstance.postDoorlockDevicesByIdUpdate(id, postDoorlockDevicesByIdUpdateRequest)
            //result shouldBe ("TODO")
        }

        // to test postDoorlockDevicesUpdate
        should("test postDoorlockDevicesUpdate") {
            // uncomment below to test postDoorlockDevicesUpdate
            //val postDoorlockDevicesByIdUpdateRequest : PostDoorlockDevicesByIdUpdateRequest =  // PostDoorlockDevicesByIdUpdateRequest | 
            //val result : PostDoorlockDevicesUpdate200Response = apiInstance.postDoorlockDevicesUpdate(postDoorlockDevicesByIdUpdateRequest)
            //result shouldBe ("TODO")
        }

        // to test postDoorlockSelfCardsByIdActivate
        should("test postDoorlockSelfCardsByIdActivate") {
            // uncomment below to test postDoorlockSelfCardsByIdActivate
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val postDoorlockSelfCardsByIdActivateRequest : PostDoorlockSelfCardsByIdActivateRequest =  // PostDoorlockSelfCardsByIdActivateRequest | 
            //val result : PostDoorlockSelfCardsByIdActivate200Response = apiInstance.postDoorlockSelfCardsByIdActivate(id, postDoorlockSelfCardsByIdActivateRequest)
            //result shouldBe ("TODO")
        }

        // to test putDoorlockCardsById
        should("test putDoorlockCardsById") {
            // uncomment below to test putDoorlockCardsById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val putDoorlockCardsByIdRequest : PutDoorlockCardsByIdRequest =  // PutDoorlockCardsByIdRequest | 
            //val result : PostDoorlockCards201Response = apiInstance.putDoorlockCardsById(id, putDoorlockCardsByIdRequest)
            //result shouldBe ("TODO")
        }

        // to test putDoorlockDevicesById
        should("test putDoorlockDevicesById") {
            // uncomment below to test putDoorlockDevicesById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val putDoorlockDevicesByIdRequest : PutDoorlockDevicesByIdRequest =  // PutDoorlockDevicesByIdRequest | 
            //val result : PostDoorlockDevices201Response = apiInstance.putDoorlockDevicesById(id, putDoorlockDevicesByIdRequest)
            //result shouldBe ("TODO")
        }

        // to test putDoorlockSelfCardsByIdFrozen
        should("test putDoorlockSelfCardsByIdFrozen") {
            // uncomment below to test putDoorlockSelfCardsByIdFrozen
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val putDoorlockSelfCardsByIdFrozenRequest : PutDoorlockSelfCardsByIdFrozenRequest =  // PutDoorlockSelfCardsByIdFrozenRequest | 
            //val result : PostDoorlockCards201Response = apiInstance.putDoorlockSelfCardsByIdFrozen(id, putDoorlockSelfCardsByIdFrozenRequest)
            //result shouldBe ("TODO")
        }

    }
}
