/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.GroupApi
import hu.petrik.filcapp.api.model.GetTimetableGroupsGetForCohortByCohortId200ResponseInner
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostTimetableGroupsSelect200Response
import hu.petrik.filcapp.api.model.PostTimetableGroupsSelectRequest

class GroupApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GroupApi
        //val apiInstance = GroupApi()

        // to test getTimetableGroupsGetForCohortByCohortId
        should("test getTimetableGroupsGetForCohortByCohortId") {
            // uncomment below to test getTimetableGroupsGetForCohortByCohortId
            //val cohortId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : kotlin.collections.List<GetTimetableGroupsGetForCohortByCohortId200ResponseInner> = apiInstance.getTimetableGroupsGetForCohortByCohortId(cohortId)
            //result shouldBe ("TODO")
        }

        // to test postTimetableGroupsSelect
        should("test postTimetableGroupsSelect") {
            // uncomment below to test postTimetableGroupsSelect
            //val postTimetableGroupsSelectRequest : PostTimetableGroupsSelectRequest =  // PostTimetableGroupsSelectRequest | 
            //val result : PostTimetableGroupsSelect200Response = apiInstance.postTimetableGroupsSelect(postTimetableGroupsSelectRequest)
            //result shouldBe ("TODO")
        }

    }
}
