/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.HealthApi
import hu.petrik.filcapp.api.model.GetHealth200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response

class HealthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthApi
        //val apiInstance = HealthApi()

        // to test getHealth
        should("test getHealth") {
            // uncomment below to test getHealth
            //val result : GetHealth200Response = apiInstance.getHealth()
            //result shouldBe ("TODO")
        }

    }
}
