/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.ImportApi
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdate200Response
import hu.petrik.filcapp.api.model.PostTimetableImportRequest

class ImportApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImportApi
        //val apiInstance = ImportApi()

        // to test postTimetableImport
        should("test postTimetableImport") {
            // uncomment below to test postTimetableImport
            //val postTimetableImportRequest : PostTimetableImportRequest =  // PostTimetableImportRequest | 
            //val result : PostDoorlockDevicesByIdUpdate200Response = apiInstance.postTimetableImport(postTimetableImportRequest)
            //result shouldBe ("TODO")
        }

    }
}
