/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.KioskApi
import hu.petrik.filcapp.api.model.GetKiosk200Response
import hu.petrik.filcapp.api.model.GetKioskNews200Response
import hu.petrik.filcapp.api.model.GetKioskPetrikNews200Response
import hu.petrik.filcapp.api.model.GetKioskWeather200Response
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostKiosk201Response
import hu.petrik.filcapp.api.model.PostKioskDepartures200Response
import hu.petrik.filcapp.api.model.PostKioskDeparturesRequest
import hu.petrik.filcapp.api.model.PostKioskHeartbeat200Response
import hu.petrik.filcapp.api.model.PostKioskHeartbeatRequest
import hu.petrik.filcapp.api.model.PostKioskRequest
import hu.petrik.filcapp.api.model.PutKioskByIdRequest

class KioskApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KioskApi
        //val apiInstance = KioskApi()

        // to test deleteKioskById
        should("test deleteKioskById") {
            // uncomment below to test deleteKioskById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : PostKiosk201Response = apiInstance.deleteKioskById(id)
            //result shouldBe ("TODO")
        }

        // to test getKiosk
        should("test getKiosk") {
            // uncomment below to test getKiosk
            //val result : GetKiosk200Response = apiInstance.getKiosk()
            //result shouldBe ("TODO")
        }

        // to test getKioskNews
        should("test getKioskNews") {
            // uncomment below to test getKioskNews
            //val result : GetKioskNews200Response = apiInstance.getKioskNews()
            //result shouldBe ("TODO")
        }

        // to test getKioskNewsByIdImage
        should("test getKioskNewsByIdImage") {
            // uncomment below to test getKioskNewsByIdImage
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : kotlin.String = apiInstance.getKioskNewsByIdImage(id)
            //result shouldBe ("TODO")
        }

        // to test getKioskPetrikNews
        should("test getKioskPetrikNews") {
            // uncomment below to test getKioskPetrikNews
            //val machine : kotlin.String = machine_example // kotlin.String | 
            //val result : GetKioskPetrikNews200Response = apiInstance.getKioskPetrikNews(machine)
            //result shouldBe ("TODO")
        }

        // to test getKioskWeather
        should("test getKioskWeather") {
            // uncomment below to test getKioskWeather
            //val result : GetKioskWeather200Response = apiInstance.getKioskWeather()
            //result shouldBe ("TODO")
        }

        // to test postKiosk
        should("test postKiosk") {
            // uncomment below to test postKiosk
            //val postKioskRequest : PostKioskRequest =  // PostKioskRequest | 
            //val result : PostKiosk201Response = apiInstance.postKiosk(postKioskRequest)
            //result shouldBe ("TODO")
        }

        // to test postKioskDepartures
        should("test postKioskDepartures") {
            // uncomment below to test postKioskDepartures
            //val postKioskDeparturesRequest : PostKioskDeparturesRequest =  // PostKioskDeparturesRequest | 
            //val result : PostKioskDepartures200Response = apiInstance.postKioskDepartures(postKioskDeparturesRequest)
            //result shouldBe ("TODO")
        }

        // to test postKioskHeartbeat
        should("test postKioskHeartbeat") {
            // uncomment below to test postKioskHeartbeat
            //val postKioskHeartbeatRequest : PostKioskHeartbeatRequest =  // PostKioskHeartbeatRequest | 
            //val result : PostKioskHeartbeat200Response = apiInstance.postKioskHeartbeat(postKioskHeartbeatRequest)
            //result shouldBe ("TODO")
        }

        // to test putKioskById
        should("test putKioskById") {
            // uncomment below to test putKioskById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val putKioskByIdRequest : PutKioskByIdRequest =  // PutKioskByIdRequest | 
            //val result : PostKiosk201Response = apiInstance.putKioskById(id, putKioskByIdRequest)
            //result shouldBe ("TODO")
        }

    }
}
