/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.MovedLessonApi
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableMovedLessons200ResponseInnerMovedLesson
import hu.petrik.filcapp.api.model.PostTimetableMovedLessonsRequest

class MovedLessonApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovedLessonApi
        //val apiInstance = MovedLessonApi()

        // to test getTimetableMovedLessons
        should("test getTimetableMovedLessons") {
            // uncomment below to test getTimetableMovedLessons
            //val result : kotlin.collections.List<GetTimetableMovedLessons200ResponseInner> = apiInstance.getTimetableMovedLessons()
            //result shouldBe ("TODO")
        }

        // to test getTimetableMovedLessonsCohortByCohortId
        should("test getTimetableMovedLessonsCohortByCohortId") {
            // uncomment below to test getTimetableMovedLessonsCohortByCohortId
            //val cohortId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : kotlin.collections.List<GetTimetableMovedLessons200ResponseInner> = apiInstance.getTimetableMovedLessonsCohortByCohortId(cohortId)
            //result shouldBe ("TODO")
        }

        // to test getTimetableMovedLessonsRelevant
        should("test getTimetableMovedLessonsRelevant") {
            // uncomment below to test getTimetableMovedLessonsRelevant
            //val result : kotlin.collections.List<GetTimetableMovedLessons200ResponseInner> = apiInstance.getTimetableMovedLessonsRelevant()
            //result shouldBe ("TODO")
        }

        // to test postTimetableMovedLessons
        should("test postTimetableMovedLessons") {
            // uncomment below to test postTimetableMovedLessons
            //val postTimetableMovedLessonsRequest : PostTimetableMovedLessonsRequest =  // PostTimetableMovedLessonsRequest | 
            //val result : GetTimetableMovedLessons200ResponseInnerMovedLesson = apiInstance.postTimetableMovedLessons(postTimetableMovedLessonsRequest)
            //result shouldBe ("TODO")
        }

    }
}
