/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.NewsSystemMessagesApi
import hu.petrik.filcapp.api.model.DeleteNewsAnnouncementsById200Response
import hu.petrik.filcapp.api.model.GetNewsSystemMessages200Response
import hu.petrik.filcapp.api.model.GetNewsSystemMessages200ResponseDataInner
import hu.petrik.filcapp.api.model.PatchNewsSystemMessagesByIdRequest
import hu.petrik.filcapp.api.model.PostNewsSystemMessages201Response
import hu.petrik.filcapp.api.model.PostNewsSystemMessagesRequest

class NewsSystemMessagesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NewsSystemMessagesApi
        //val apiInstance = NewsSystemMessagesApi()

        // to test deleteNewsSystemMessagesById
        should("test deleteNewsSystemMessagesById") {
            // uncomment below to test deleteNewsSystemMessagesById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : DeleteNewsAnnouncementsById200Response = apiInstance.deleteNewsSystemMessagesById(id)
            //result shouldBe ("TODO")
        }

        // to test getNewsSystemMessages
        should("test getNewsSystemMessages") {
            // uncomment below to test getNewsSystemMessages
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val includeAll : kotlin.String = includeAll_example // kotlin.String | 
            //val includeExpired : kotlin.String = includeExpired_example // kotlin.String | 
            //val includeKioskOnly : kotlin.String = includeKioskOnly_example // kotlin.String | 
            //val result : GetNewsSystemMessages200Response = apiInstance.getNewsSystemMessages(limit, offset, includeAll, includeExpired, includeKioskOnly)
            //result shouldBe ("TODO")
        }

        // to test getNewsSystemMessagesById
        should("test getNewsSystemMessagesById") {
            // uncomment below to test getNewsSystemMessagesById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : GetNewsSystemMessages200ResponseDataInner = apiInstance.getNewsSystemMessagesById(id)
            //result shouldBe ("TODO")
        }

        // to test patchNewsSystemMessagesById
        should("test patchNewsSystemMessagesById") {
            // uncomment below to test patchNewsSystemMessagesById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val patchNewsSystemMessagesByIdRequest : PatchNewsSystemMessagesByIdRequest =  // PatchNewsSystemMessagesByIdRequest | 
            //val result : PostNewsSystemMessages201Response = apiInstance.patchNewsSystemMessagesById(id, patchNewsSystemMessagesByIdRequest)
            //result shouldBe ("TODO")
        }

        // to test postNewsSystemMessages
        should("test postNewsSystemMessages") {
            // uncomment below to test postNewsSystemMessages
            //val postNewsSystemMessagesRequest : PostNewsSystemMessagesRequest =  // PostNewsSystemMessagesRequest | 
            //val result : PostNewsSystemMessages201Response = apiInstance.postNewsSystemMessages(postNewsSystemMessagesRequest)
            //result shouldBe ("TODO")
        }

    }
}
