/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.NewsApi
import hu.petrik.filcapp.api.model.ErrorResponse
import hu.petrik.filcapp.api.model.GetAnnouncementById200Response
import hu.petrik.filcapp.api.model.GetAnnouncements200Response
import hu.petrik.filcapp.api.model.GetBlogById200Response
import hu.petrik.filcapp.api.model.GetBlogs200Response
import hu.petrik.filcapp.api.model.GetSystemMessageById200Response
import hu.petrik.filcapp.api.model.GetSystemMessages200Response

class NewsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NewsApi
        //val apiInstance = NewsApi()

        // to test getAnnouncementById
        should("test getAnnouncementById") {
            // uncomment below to test getAnnouncementById
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : GetAnnouncementById200Response = apiInstance.getAnnouncementById(id)
            //result shouldBe ("TODO")
        }

        // to test getAnnouncements
        should("test getAnnouncements") {
            // uncomment below to test getAnnouncements
            //val result : GetAnnouncements200Response = apiInstance.getAnnouncements()
            //result shouldBe ("TODO")
        }

        // to test getBlogById
        should("test getBlogById") {
            // uncomment below to test getBlogById
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : GetBlogById200Response = apiInstance.getBlogById(id)
            //result shouldBe ("TODO")
        }

        // to test getBlogBySlug
        should("test getBlogBySlug") {
            // uncomment below to test getBlogBySlug
            //val slug : kotlin.String = slug_example // kotlin.String | 
            //val result : GetBlogById200Response = apiInstance.getBlogBySlug(slug)
            //result shouldBe ("TODO")
        }

        // to test getBlogs
        should("test getBlogs") {
            // uncomment below to test getBlogs
            //val result : GetBlogs200Response = apiInstance.getBlogs()
            //result shouldBe ("TODO")
        }

        // to test getSystemMessageById
        should("test getSystemMessageById") {
            // uncomment below to test getSystemMessageById
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : GetSystemMessageById200Response = apiInstance.getSystemMessageById(id)
            //result shouldBe ("TODO")
        }

        // to test getSystemMessages
        should("test getSystemMessages") {
            // uncomment below to test getSystemMessages
            //val result : GetSystemMessages200Response = apiInstance.getSystemMessages()
            //result shouldBe ("TODO")
        }

    }
}
