/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.NewsAnnouncementsApi
import hu.petrik.filcapp.api.model.DeleteNewsAnnouncementsById200Response
import hu.petrik.filcapp.api.model.GetNewsAnnouncements200Response
import hu.petrik.filcapp.api.model.GetNewsAnnouncements200ResponseDataInner
import hu.petrik.filcapp.api.model.PatchNewsAnnouncementsByIdRequest
import hu.petrik.filcapp.api.model.PostNewsAnnouncements201Response
import hu.petrik.filcapp.api.model.PostNewsAnnouncementsRequest

class NewsAnnouncementsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NewsAnnouncementsApi
        //val apiInstance = NewsAnnouncementsApi()

        // to test deleteNewsAnnouncementsById
        should("test deleteNewsAnnouncementsById") {
            // uncomment below to test deleteNewsAnnouncementsById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : DeleteNewsAnnouncementsById200Response = apiInstance.deleteNewsAnnouncementsById(id)
            //result shouldBe ("TODO")
        }

        // to test getNewsAnnouncements
        should("test getNewsAnnouncements") {
            // uncomment below to test getNewsAnnouncements
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val includeAll : kotlin.String = includeAll_example // kotlin.String | 
            //val includeExpired : kotlin.String = includeExpired_example // kotlin.String | 
            //val includeKioskOnly : kotlin.String = includeKioskOnly_example // kotlin.String | 
            //val result : GetNewsAnnouncements200Response = apiInstance.getNewsAnnouncements(limit, offset, includeAll, includeExpired, includeKioskOnly)
            //result shouldBe ("TODO")
        }

        // to test getNewsAnnouncementsById
        should("test getNewsAnnouncementsById") {
            // uncomment below to test getNewsAnnouncementsById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : GetNewsAnnouncements200ResponseDataInner = apiInstance.getNewsAnnouncementsById(id)
            //result shouldBe ("TODO")
        }

        // to test patchNewsAnnouncementsById
        should("test patchNewsAnnouncementsById") {
            // uncomment below to test patchNewsAnnouncementsById
            //val id : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val patchNewsAnnouncementsByIdRequest : PatchNewsAnnouncementsByIdRequest =  // PatchNewsAnnouncementsByIdRequest | 
            //val result : PostNewsAnnouncements201Response = apiInstance.patchNewsAnnouncementsById(id, patchNewsAnnouncementsByIdRequest)
            //result shouldBe ("TODO")
        }

        // to test postNewsAnnouncements
        should("test postNewsAnnouncements") {
            // uncomment below to test postNewsAnnouncements
            //val postNewsAnnouncementsRequest : PostNewsAnnouncementsRequest =  // PostNewsAnnouncementsRequest | 
            //val result : PostNewsAnnouncements201Response = apiInstance.postNewsAnnouncements(postNewsAnnouncementsRequest)
            //result shouldBe ("TODO")
        }

    }
}
