/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.RolesApi
import hu.petrik.filcapp.api.model.GetRoles200Response
import hu.petrik.filcapp.api.model.PatchRolesByNameRequest
import hu.petrik.filcapp.api.model.PostBugReport400Response
import hu.petrik.filcapp.api.model.PostDoorlockDevicesByIdUpdate200Response
import hu.petrik.filcapp.api.model.PostRoles201Response
import hu.petrik.filcapp.api.model.PostRolesRequest

class RolesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RolesApi
        //val apiInstance = RolesApi()

        // to test deleteRolesByName
        should("test deleteRolesByName") {
            // uncomment below to test deleteRolesByName
            //val name : kotlin.String = name_example // kotlin.String | 
            //val result : PostDoorlockDevicesByIdUpdate200Response = apiInstance.deleteRolesByName(name)
            //result shouldBe ("TODO")
        }

        // to test getRoles
        should("test getRoles") {
            // uncomment below to test getRoles
            //val result : GetRoles200Response = apiInstance.getRoles()
            //result shouldBe ("TODO")
        }

        // to test getRolesPermissions
        should("test getRolesPermissions") {
            // uncomment below to test getRolesPermissions
            //val result : PatchRolesByNameRequest = apiInstance.getRolesPermissions()
            //result shouldBe ("TODO")
        }

        // to test patchRolesByName
        should("test patchRolesByName") {
            // uncomment below to test patchRolesByName
            //val name : kotlin.String = name_example // kotlin.String | 
            //val patchRolesByNameRequest : PatchRolesByNameRequest =  // PatchRolesByNameRequest | 
            //val result : PostRoles201Response = apiInstance.patchRolesByName(name, patchRolesByNameRequest)
            //result shouldBe ("TODO")
        }

        // to test postRoles
        should("test postRoles") {
            // uncomment below to test postRoles
            //val postRolesRequest : PostRolesRequest =  // PostRolesRequest | 
            //val result : PostRoles201Response = apiInstance.postRoles(postRolesRequest)
            //result shouldBe ("TODO")
        }

    }
}
