/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.SubjectApi
import hu.petrik.filcapp.api.model.GetTimetableSubjects200ResponseInner
import hu.petrik.filcapp.api.model.PostBugReport400Response

class SubjectApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubjectApi
        //val apiInstance = SubjectApi()

        // to test getTimetableSubjects
        should("test getTimetableSubjects") {
            // uncomment below to test getTimetableSubjects
            //val result : kotlin.collections.List<GetTimetableSubjects200ResponseInner> = apiInstance.getTimetableSubjects()
            //result shouldBe ("TODO")
        }

    }
}
