/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.SubstitutionApi
import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInner
import hu.petrik.filcapp.api.model.GetTimetableSubstitutions200ResponseInnerSubstitution
import hu.petrik.filcapp.api.model.GetTimetableSubstitutionsCohortByCohortId200Response
import hu.petrik.filcapp.api.model.GetTimetableSubstitutionsRelevant200ResponseInner
import hu.petrik.filcapp.api.model.PostTimetableSubstitutionsRequest

class SubstitutionApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubstitutionApi
        //val apiInstance = SubstitutionApi()

        // to test getTimetableSubstitutions
        should("test getTimetableSubstitutions") {
            // uncomment below to test getTimetableSubstitutions
            //val result : kotlin.collections.List<GetTimetableSubstitutions200ResponseInner> = apiInstance.getTimetableSubstitutions()
            //result shouldBe ("TODO")
        }

        // to test getTimetableSubstitutionsCohortByCohortId
        should("test getTimetableSubstitutionsCohortByCohortId") {
            // uncomment below to test getTimetableSubstitutionsCohortByCohortId
            //val cohortId : kotlin.String = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.String | 
            //val result : GetTimetableSubstitutionsCohortByCohortId200Response = apiInstance.getTimetableSubstitutionsCohortByCohortId(cohortId)
            //result shouldBe ("TODO")
        }

        // to test getTimetableSubstitutionsRelevant
        should("test getTimetableSubstitutionsRelevant") {
            // uncomment below to test getTimetableSubstitutionsRelevant
            //val result : kotlin.collections.List<GetTimetableSubstitutionsRelevant200ResponseInner> = apiInstance.getTimetableSubstitutionsRelevant()
            //result shouldBe ("TODO")
        }

        // to test postTimetableSubstitutions
        should("test postTimetableSubstitutions") {
            // uncomment below to test postTimetableSubstitutions
            //val postTimetableSubstitutionsRequest : PostTimetableSubstitutionsRequest =  // PostTimetableSubstitutionsRequest | 
            //val result : GetTimetableSubstitutions200ResponseInnerSubstitution = apiInstance.postTimetableSubstitutions(postTimetableSubstitutionsRequest)
            //result shouldBe ("TODO")
        }

    }
}
