/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.petrik.filcapp.api.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hu.petrik.filcapp.api.client.UsersApi
import hu.petrik.filcapp.api.model.ErrorResponse
import hu.petrik.filcapp.api.model.GetUsers200Response

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test getUsers
        should("test getUsers") {
            // uncomment below to test getUsers
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | 
            //val result : GetUsers200Response = apiInstance.getUsers(limit, offset, search)
            //result shouldBe ("TODO")
        }

    }
}
